### PR TITLE
GitHub has a capital H

### PR DESCRIPTION
**Pull request by singingwolfboy**
Just fixing a pet peeve of mine.

### CODE REVIEW

**Comment by uranusjr** [comment]
The last one you’ll need to submit to pip (notpip is a patched version of it), otherwise I have no objections.

**Comment by singingwolfboy** [comment]
@uranusjr: looks like [that's already been done](https://github.com/pypa/pip/commit/508517f0d7898618d656310ddd797200944b0136).

**Comment by uranusjr** [comment]
Ah that’s great news. Could you remove the change on notpip then? We’ll be able to apply the upstream change once we upgrade, and the change would cause merge conflicts when we do that.

**Comment by singingwolfboy** [comment]
@uranusjr: OK, I've reverted that change.

**Pull request merged**
