### PR TITLE
Add test for setup.py::dependency-link field

### PR DESCRIPTION
**Pull request by atzannes**
##### The issue

Issue #2613 was fixed via #2643, but the fix did not include a regression test.

##### The fix

This pull request proposes an integration test that failed prior to #2643 but succeeds now.
By taking a look at #2643 it wasn't clear to me how to write a unit test instead of this integration test. Because this integration test relies on web connectivity to a github repository, I created a dummy repo to be used just by this test. I suspect it is preferable to fork that repo under the `pypa` org so as not to have it under my personal account though.

##### The checklist

* [x] Associated issue #2613 
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

There doesn't seem to be a relevant fragment for just adding a regression test

### CODE REVIEW

**Comment by techalchemy** [comment]
```

**Comment by atzannes** [comment]
Any chance I can get invited to the Build Kite org? What would really simplify me iterating and figuring out how to fix this is seeing how the tests are failing each time. In our org we use CircleCI and there are some per-project settings that I configured for accessing private repositories. This is not the case here, but I imagine we may need SSH keys to be set up nevertheless

**Comment by techalchemy** [comment]
Ah I think i see the issue:

```console
Could not fetch URL http://127.0.0.1:38445/simple/test-private-dependency/: 404 Client Error: NOT FOUND for url: http://127.0.0.1:38445/simple/test-private-dependency/ - skipping
Cleaning up...
Removed build tracker '/tmp/pip-req-tracker-vXvve7'
Exception information:
Traceback (most recent call last):
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 299, in run
    resolver.resolve(requirement_set)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 218, in prepare_linked_requirement
    req.populate_link(finder, upgrade_allowed, require_hashes)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/req/req_install.py", line 308, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/tmp/pipenv-DqaIHC-project/.venv/local/lib/python2.7/site-packages/pip/_internal/index.py", line 543, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for test-private-dependency (from testdeplinks==0.1)
1 location(s) to search for versions of pip:
* http://127.0.0.1:38445/simple/pip/
Getting page http://127.0.0.1:38445/simple/pip/
Starting new HTTP connection (1): 127.0.0.1:38445
http://127.0.0.1:38445 "GET /simple/pip/ HTTP/1.1" 404 233
Could not fetch URL http://127.0.0.1:38445/simple/pip/: 404 Client Error: NOT FOUND for url: http://127.0.0.1:38445/simple/pip/ - skipping
```

I think you need to mark this with `needs_internet` and remove the `pypi` argument everywhere it occurs so we stop trying to retrieve info about it from the mocked index.  If tests continue to fail you can first check for the `return_code` from the installation and if it is non-zero you can print `c.err` for better debugging and I can pass that along

**Comment by techalchemy** [comment]
Hm I think i was wrong, but I made one small change to your branch (hope you don't mind) which was to add the environment variable `PIP_PROCESS_DEPENDENCY_LINKS` using the `temp_environ` context manager we have setup.  Without any instruction otherwise, pip doesn't actually use the information in `dependency_links`

**Comment by atzannes** [comment]
Awesome, thanks for the help @techalchemy! I'm trying out some alternatives to include a test for a git+ssh dependency link, and I should have something more polished and ready to merge soon.

**Comment by atzannes** [comment]
Ready to merge on my side

**Comment by atzannes** [comment]
@techalchemy ready to merge on my side (forgot to at-mention before)

**Comment by techalchemy** [comment]
thanks, sorry for the delay!

**Pull request merged**
