### PR TITLE
Revert "Clean up temporary files created during installation"

### PR DESCRIPTION
**Pull request by techalchemy**
Reverts pypa/pipenv#1233

- This breaks everything on windows

### CODE REVIEW

**Comment by nateprewitt** [comment]
Yeah, this is why we weren’t merging anything till Appveyor was running properly. Was there any issue open with the previous PR that we can open back up to track this?

**Comment by nateprewitt** [comment]
#1273 will be the tracking issue for this. Thanks for catching this @techalchemy!

**Comment by uranusjr** [comment]
I haven’t tried, but why does it break on Windows? Is it because Windows have issues deleting files with handled held by processes?

**Comment by techalchemy** [comment]
@uranusjr that is correct. However I have a rework that won't require a full revert i think

**Pull request merged**
