### PR TITLE
Pipfile: Added feature for enabling && character

### PR DESCRIPTION
**Pull request by tapaswenipathak**
### The issue

Fixes https://github.com/pypa/pipenv/issues/3919.

### The fix

Feel free letting me know if you require any behavioral changes or tests for the added feature.

### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog).

### CODE REVIEW

**Comment by frostming** [comment]
Your fix doesn't relate to the original issue. In fact `tasks/` folder has nothing to do with the `pipenv` executable.

Thanks for your effort but I would like to reject this now. Feel free to open another PR when you have a true fix.

**Comment by tapaswenipathak** [comment]
@frostming: The time when release command is run having multiple commands both commands should run. What you think is incorrect? Can you please tell me the correct directory?

**Comment by frostming** [comment]
@tapaswenipathak `tasks/release.py` is a dev script for releasing the project, and under dry run mode no actions should be taken.

The original issue is complaining about the `pipenv run [script_name]`, where `script_name` is defined in `Pipfile`, which doesn't support compound commands that contain `&&`. The correct file is `pipenv/core.py:do_run` and further `pipenv/cmdparse.py`

**Comment by tapaswenipathak** [comment]
I see, nice!

**Pull request closed without merging**
