### PR TITLE
Prevent a crash in version check error message

### LINKED ISSUE #3407: Pipenv crash when the virtualenv is corrupt
A virtualenv can become corrupt if the version of python used to create the virtualenv is no longer available.

Then upon invoking pipenv, this can happen:

```pytb
  Traceback (most recent call last):
  File "/usr/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==2018.11.15.dev0', 'console_scripts', 'pipenv')()
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pipenv/cli/command.py", line 319, in lock
    ensure_project(three=state.three, python=state.python, pypi_mirror=state.pypi_mirror)
  File "/usr/lib/python3.7/site-packages/pipenv/core.py", line 590, in ensure_project
    crayons.green(shorten_path(path_to_python)),
TypeError: __str__ returned non-string (type NoneType)
```

This is the code in question:

```py

            if project.required_python_version:
                path_to_python = which("python") or which("py")
                if path_to_python and project.required_python_version not in (
                    python_version(path_to_python) or ""
                ):
                    click.echo(
                        "{0}: Your Pipfile requires {1} {2}, "
                        "but you are using {3} ({4}).".format(
                            crayons.red("Warning", bold=True),
                            crayons.normal("python_version", bold=True),
                            crayons.blue(project.required_python_version),
                            crayons.blue(python_version(path_to_python)),
                            crayons.green(shorten_path(path_to_python)),
                        ),
                        err=True,
                    )
```

`python_version(path_to_python)` returns `None`. This causes `crayons.blue(python_version(path_to_python))` to crash. Proposed fix in #3408.

### PR DESCRIPTION
**Pull request by jleclanche**
Fixes #3407

### CODE REVIEW

**Comment by jxltom** [comment]
What is the path of ```path_to_python```? Maybe it is better to fix this issue in ```which("python")``` or ```which("py")```?

**Comment by jleclanche** [comment]
The path is a path string pointing to a broken symlink

**Comment by jxltom** [comment]
It is just warning which won't abort the operation since it is just version mismatch and the python path is still valid. Pipenv could still proceed operations such as locking, installing, etc. But with invalid python path, I'm not sure whether silent this exception could raise other issues in further steps.

**Comment by jleclanche** [comment]
hm, maybe. I didn't really try it out much further, just wanted to file the pr+issue so it doesnt get hit again but feel free to try a different approach.

**Comment by jxltom** [comment]
Sure, this is definitely a bug or something needs enhancement. Thanks for this! We just need to make sure the patch shouldn't have any side effects.

**Comment by techalchemy** [comment]
thanks!

**Pull request merged**
