### PR TITLE
Update Python 3.3 and 3.6 versions

### PR DESCRIPTION
**Pull request by berkerpeksag**
* 3.3.7 was released on 2017-09-19
* 3.6.4 was released on 2017-12-19

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Test failure is unrelated to this PR and it will be resolved by the commit b9b29df0629dd27652d29b4738eda32f847377c2 in PR #1361.

**Comment by nateprewitt** [comment]
@berkerpeksag would you mind rebasing this onto the current master? Thanks!

**Comment by berkerpeksag** [comment]
@nateprewitt done (but it looks like the Appveyor builds got stuck)

**Comment by nateprewitt** [comment]
@berkerpeksag I believe they're queued behind other builds. They should start shortly.

**Pull request merged**
