### PR TITLE
Implement our own subshell logic

### LINKED ISSUE #915: pipenv shell starts a CMD shell when run from powershell
I use powershell as my primary shell, but `pipenv shell` starts a CMD prompt.

##### Describe you environment

1. OS Type: Windows 7
1. Python version: `$ python -V` 3.6.2
1. Pipenv version: `$ pipenv --version` 8.2.6

##### Expected result

I'd expect the shell that was started to be the same as my current shell (i.e., powershell)

##### Actual result

The shell is always a CMD shell, as far as I can see there is no way to change this.

##### Steps to replicate

`pipenv shell`. It's possible to work around this by using `pipenv run powershell` but this doesn't set `$env:VIRTUAL_ENV` (which I believe is a known issue).

### PR DESCRIPTION
**Pull request by uranusjr**
Remove all `pew workon` usages, and implement the subshell functionality from scratch based on Shellingham.

With real shell detection on POSIX implemented, the subshell now defaults to match parent shell, instead of login shell. This would help reduce surprising behaviour such as #1762.

I tested the code on Windows and Ubuntu (WSL) in both fancy and compat mode, and am fairly confident this implementation is reasonably complete. It would probably still be a good idea to rigorously test this manually on various platforms before releasing it to the public.

This also fixes #915 (a bug in Pew).

### CODE REVIEW

**Comment by uranusjr** [comment]
I think this is ready. This can only get more manual testing if merged into master.

**Comment by techalchemy** [comment]
merging!

**Comment by mungojam** [comment]
I'm surprised that this doesn't seem to fix #876 since that was a bug with pew. Is there a different bug with Shellingham?

**Comment by uranusjr** [comment]
Unfortunately Shellingham does many things the same as Pew. It fixes a lot of things, but not all of them. But it’d be possible to work on it now, at least.

**Pull request merged**
