### PR TITLE
added all available system variable

### PR DESCRIPTION
**Pull request by Abdullium**
Just below the "Custom Virtual Environment Location" I have added all the system environment variable

Thank you for contributing to Pipenv!

### The issue

What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.

Always consider opening an issue first to describe your problem, so we can discuss what is the best way to amend it.  Note that if you do not describe the goal of this change or link to a related issue, the maintainers may close the PR without further review.

If your pull request makes a non-insignificant change to Pipenv, such as the user interface or intended functionality, please file a PEEP.

    https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md

### The fix

How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?

### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by oz123** [comment]
This approach requires manual labor to document the variables if they are removed or added.
Please see my branch here:
https://github.com/pypa/pipenv/tree/document-environment-variables

You can steal this code, and add the news fragment to finish my PR.

**Comment by Abdullium** [comment]
> This approach requires manual labor to document the variables if they are removed or added. Please see my branch here: https://github.com/pypa/pipenv/tree/document-environment-variables
> 
> You can steal this code, and add the news fragment to finish my PR.

So you want me to write a command which prints the latest variable, and also mentions this in the news doc right?

**Comment by oz123** [comment]
Not yet. You still need to change `environments.py` and create a news entry.

**Comment by Abdullium** [comment]
> Not yet. You still need to change `environments.py` and create a news entry.

See what I suggest is that 
You can merge the request now 

And I will later raise the issue for any descrepancies

**Comment by oz123** [comment]
@Abdullium thank you for your contribution, I created a PR which fixes the issue #5235 .

**Pull request closed without merging**
