### PR TITLE
Documentation specifiers#2816

### PR DESCRIPTION
**Pull request by GilbertoCS**
### The issue

#2816 

### The fix

As requested I send my version to the documentation of the specifiers

### The checklist

* [x] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by uranusjr** [comment]
Cool! I’ll see how I can merge both versions tomorrow (or @trallard you can do it if you have time)

**Comment by trallard** [comment]
@uranusjr I had some minutes to spare and went over both PR I have made some amendments on my PR to add some bits from this PR. I tried to keep this limited to the use of specifiers we discussed in [https://github.com/pypa/pipenv/pull/2930](https://github.com/pypa/pipenv/pull/2930)

I do not know if this was the best way of doing it but it certainly incorporates both suggestions 
(cc/ @GilbertoCS in case he wants to go over this and make comments)

**Comment by GilbertoCS** [comment]
@trallard thank you for the time to merge, I like that way

**Comment by uranusjr** [comment]
Closing for #2930

**Pull request closed without merging**
