### PR TITLE
Roll back change vendoring of colorama.

### LINKED ISSUE #5458: AttributeError: 'VistirSpinner' object has no attribute '_color_func' (2022.11.4)
### Issue description

Suddenly with 2022.11.4, running `pipenv install` even on an empty directory (under Python 3.9):
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pipenv/utils/spinner.py", line 18, in create_spinner
    yield sp
  File "/usr/local/lib/python3.9/dist-packages/pipenv/core.py", line 1019, in do_create_virtualenv
    sp.green.ok(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 264, in ok
    self._freeze(_text, err=err)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 363, in _freeze
    last_frame = self._compose_out(text, mode="last")
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 386, in _compose_out
    if self._color_func is not None:
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 115, in __getattr__
    retval = super(DummySpinner, self).__getattribute__(k)
AttributeError: 'VistirSpinner' object has no attribute '_color_func'

Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/cli/command.py", line 236, in install
    do_install(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/core.py", line 2115, in do_install
    ensure_project(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/core.py", line 530, in ensure_project
    ensure_virtualenv(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/core.py", line 463, in ensure_virtualenv
    do_create_virtualenv(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/core.py", line 1019, in do_create_virtualenv
    sp.green.ok(
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 264, in ok
    self._freeze(_text, err=err)
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 363, in _freeze
    last_frame = self._compose_out(text, mode="last")
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 386, in _compose_out
    if self._color_func is not None:
  File "/usr/local/lib/python3.9/dist-packages/pipenv/vendor/vistir/spin.py", line 115, in __getattr__
    retval = super(DummySpinner, self).__getattribute__(k)
AttributeError: 'VistirSpinner' object has no attribute '_color_func'
```

Nothing additional from verbose.

-------------------------------------------------------------------------------

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2022.11.4'`

Pipenv location: `'/usr/local/lib/python3.9/dist-packages/pipenv'`

Python location: `'/usr/bin/python3.9'`

OS Name: `'posix'`

User pip version: `'22.3'`

user Python installations found:

  - `3.9.15`: `/usr/bin/python3.9`
  - `3.6.9`: `/usr/bin/python3.6`
  - `3.6.9`: `/usr/bin/python3.6m`
  - `3.6.9`: `/usr/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.9.15',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '5.15.49-linuxkit',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Tue Sep 13 07:51:32 UTC 2022',
 'python_full_version': '3.9.15',
 'python_version': '3.9',
 'sys_platform': 'linux'}
```

System environment variables:

  - `OLDPWD`
  - `_`
  - `PATH`
  - `CERTIFICATES_ARG`
  - `SHLVL`
  - `TERM`
  - `DEBIAN_FRONTEND`
  - `HOME`
  - `PWD`
  - `DISPLAY`
  - `LANG`
  - `LS_COLORS`
  - `LC_ALL`
  - `GRPC_POLL_STRATEGY`
  - `PIP_DISABLE_PIP_VERSION_CHECK`
  - `PIP_PYTHON_PATH`
  - `PYTHONDONTWRITEBYTECODE`
  - `PYTHONFINDER_IGNORE_UNSUPPORTED`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/app/foo`

---------------------------

</details>

### LINKED ISSUE #5459: Gitlab-Pipeline Crash after new release 2022.11.4
Our build crashes with the new release of pipenv:

Collecting pipenv
  Downloading pipenv-2022.11.4-py2.py3-none-any.whl (2.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB [42](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L42).9 MB/s eta 0:00:00
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)
Collecting certifi
  Downloading certifi-2022.9.24-py3-none-any.whl (161 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.1/161.1 KB 32.1 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.8/site-packages (from pipenv) (57.5.0)
Collecting virtualenv
  Downloading virtualenv-20.16.6-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 65.5 MB/s eta 0:00:00
Collecting platformdirs<3,>=2.4
  Downloading platformdirs-2.5.2-py3-none-any.whl (14 kB)
Collecting filelock<4,>=3.4.1
  Downloading filelock-3.8.0-py3-none-any.whl (10 kB)
Collecting distlib<1,>=0.3.6
  Downloading distlib-0.3.6-py2.py3-none-any.whl ([46](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L46)8 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 KB 75.2 MB/s eta 0:00:00
Installing collected packages: distlib, virtualenv-clone, platformdirs, filelock, certifi, virtualenv, pipenv
Successfully installed certifi-2022.9.24 distlib-0.3.6 filelock-3.8.0 pipenv-2022.11.4 platformdirs-2.5.2 virtualenv-20.16.6 virtualenv-clone-0.5.7
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 22.0.4; however, version 22.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
INFO[0012] Taking snapshot of full filesystem...        
INFO[0014] ENV PROJECT_DIR /app                         
INFO[0014] COPY ./src /${PROJECT_DIR}                   
INFO[0014] Taking snapshot of files...                  
INFO[0014] COPY ./Pipfile /${PROJECT_DIR}               
INFO[0014] Taking snapshot of files...                  
INFO[0014] RUN rm -rf ${PROJECT_DIR}/.env               
INFO[0014] Cmd: /bin/sh                                 
INFO[0014] Args: [-c rm -rf ${PROJECT_DIR}/.env]        
INFO[0014] Running: [/bin/sh -c rm -rf ${PROJECT_DIR}/.env] 
INFO[0014] Taking snapshot of full filesystem...        
INFO[0015] No files were changed, appending empty layer to config. No layer added to image. 
INFO[0015] WORKDIR ${PROJECT_DIR}                       
INFO[0015] Cmd: workdir                                 
INFO[0015] Changed working directory to /app            
INFO[0015] No files changed in this command, skipping snapshotting. 
INFO[0015] RUN pipenv lock                              
INFO[0015] Cmd: /bin/sh                                 
INFO[0015] Args: [-c pipenv lock]                       
INFO[0015] Running: [/bin/sh -c pipenv lock]            
Creating a virtualenv for this project...
Pipfile: /app/Pipfile
Using /usr/local/bin/python3.8 (3.8.15) to create virtualenv...
created virtual environment CPython3.8.15.final.0-64 in 811ms
  creator Venv(dest=/root/.local/share/virtualenvs/app-4PlAip0Q, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Posix)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==22.3, setuptools==65.5.0, wheel==0.37.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pipenv/utils/spinner.py", line 18, in create_spinner
    yield sp
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1019, in do_create_virtualenv
    sp.green.ok(
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 264, in ok
    self._freeze(_text, err=err)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 363, in _freeze
    last_frame = self._compose_out(text, mode="last")
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 386, in _compose_out
    if self._color_func is not None:
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 115, in __getattr__
    retval = super(DummySpinner, self).__getattribute__(k)
AttributeError: 'VistirSpinner' object has no attribute '_color_func'
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/options.py", line 57, in main
    return super().main(*args, **kwargs, windows_expand_args=False)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 10[53](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L53), in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 7[54](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L54), in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/pipenv/cli/command.py", line 328, in lock
    ensure_project(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 530, in ensure_project
    ensure_virtualenv(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 4[63](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L63), in ensure_virtualenv
    do_create_virtualenv(
  File "/usr/local/lib/python3.8/site-packages/pipenv/core.py", line 1019, in do_create_virtualenv
    sp.green.ok(
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 2[64](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L64), in ok
    self._freeze(_text, err=err)
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 363, in _freeze
    last_frame = self._compose_out(text, mode="last")
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 3[86](https://gitlab.newworkjob.de/gitlab-instance-31e781f1/frontend/-/jobs/1632#L86), in _compose_out
    if self._color_func is not None:
  File "/usr/local/lib/python3.8/site-packages/pipenv/vendor/vistir/spin.py", line 115, in __getattr__
    retval = super(DummySpinner, self).__getattribute__(k)
AttributeError: 'VistirSpinner' object has no attribute '_color_func'
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1

### PR DESCRIPTION
**Pull request by matteius**
Quick fix to roll back change of vendoring of colorama to solve issue report.

### The issue

Fixes #5458 
Fixes #5459

### CODE REVIEW

**Comment by cclauss** [comment]
Try https://pypi.org/project/rich instead?

**Comment by matteius** [comment]
@cclauss worth exploring, but pip also includes colorama and the breakage came about from trying to use that version rather than what we already had.  Only had time to fix the release, but if you want to open a ticket to explore that, seems good.

**Comment by collectiontrip** [comment]
i had same problem you can upgrade your python 11 error will gone

**Comment by oz123** [comment]
Regarding rich: I have a plan to remove the spinner class we use in favor of rich.
Rich itself uses colorama in Windows, and it isn't a replacement. However, once the Yaspin spinner from vistir is removed we definitely remove our version of colorama.

**Comment by cclauss** [comment]
The final report used to say `3 of 25 dependencies were updated` (or similar).  Would it be possible to bring that back?

**Comment by oz123** [comment]
Running which command?

**Pull request merged**
