### PR TITLE
Remove old .vsts-ci directory and its contents

### PR DESCRIPTION
**Pull request by DavidStaheli**
Now that the latest Azure Pipelines YAML files are in the `.azure-pipelines` directory (#3165), this PR removes the old `.vsts-ci` directory.

### CODE REVIEW

**Comment by techalchemy** [comment]
:tada: Was much work required on the Azure side?

Thanks again! We are already gaining some insight into which tests are flaky and which are slow, and I'm planning to spend some time deduplicating some of our test configuration

**Comment by DavidStaheli** [comment]
On the Azure side, I just cloned the existing pipelines and pointed the new ones to the YAML files in the `azure-pipelines` directory.

By the way, I noticed that the pipelines currently use OAuth to connect to GitHub as your personal GitHub identity.  If you want, you can install the Azure Pipelines GitHub App into this repository or the PyPA org from [here](https://github.com/apps/azure-pipelines).  If you do, be sure to choose the PyPA org and Pipenv project during installation setup.  Then, builds will run as the "Azure Pipelines" identity and you'll get richer build and test results in the PRs.  Please let me know if you do install the app and I'll do the minor tweak required on the Azure side.  Of course it's totally up to you!

**Comment by techalchemy** [comment]
You are so friendly like I know what I’m doing :) pretty confident I set that up before such things were possible. I’ll definitely make the change

**Comment by techalchemy** [comment]
> you can install the Azure Pipelines GitHub App into this repository or the PyPA org from here. If you do, be sure to choose the PyPA org and Pipenv project during installation setup. 

I *think* I did this, but not 100% sure, I was getting a permission error but @dstufft tells me it's turned on already

Thanks again for all the help!

**Comment by DavidStaheli** [comment]
Hi @techalchemy.  It looks like the GitHub App-based connection isn't fully set up in Azure Pipelines.  Doing so will allow the build results to show up in GitHub's Checks UI with richer detail.  But I can't do it because it requires being a repo admin.  Can you please try?  You just have to:

1. Follow [this URL](https://aex.dev.azure.com/signup/github?acquisitionId=a3779bc2-5f6e-491c-8c7d-8652d71789f3&installation_id=410220)
2. Sign in if prompted
3. Choose PyPA as the org and pipenv as the project
4. Cancel when you see the UI for creating a new pipeline (it's not necessary)

Would you mind giving it a shot?  Thanks!

image

**Comment by techalchemy** [comment]
Oh nice that actually worked! The UX on that login / Auth flow was dramatically better from whatever I was trying to do before. I have no idea what it was, or whether y’all have pushed any updates, but it even recommended a pipeline which was cool. Love seeing all the improvements!

**Comment by DavidStaheli** [comment]
Awesome!  Thanks for that feedback - it'll mean a lot to the team.  By the way, it looks like you're in the RTP area.  We're just over in Morrisville.  It would be an honor to buy you lunch sometime and hear about your work and background.

**Comment by techalchemy** [comment]
I’d love to set that up anytime, feel free to reach out via email if you like!

**Pull request merged**
