### PR TITLE
Move handling of --completion earlier to make it way faster

### PR DESCRIPTION
**Pull request by anowlcalledjosh**
More details in issue #1247, but basically:

- `pipenv.core` takes about 400ms to import
- why do that before checking if `--completion` was passed?

This takes `pipenv --completion` from taking 1.1 seconds down to only 0.6 seconds on my machine (I think it can still go faster, hopefully I'll have time to explore that more in a couple of weeks, but this seemed like an easy win).

### CODE REVIEW

**Comment by kennethreitz** [comment]
this won't work. we can't shell out the rest of our running to a subprocess.

**Comment by anowlcalledjosh** [comment]
Hm? This is still working exactly how it was before, just that completion is now handled before doing the expensive imports. All I've done is move a section of code a few lines upwards.

**Comment by kennethreitz** [comment]
you moved literally all of our code into a delegator call that will always exit 0.

**Comment by kennethreitz** [comment]
oh, i see. interesting.

**Comment by kennethreitz** [comment]
i misread

**Comment by kennethreitz** [comment]
thanks!

**Comment by anowlcalledjosh** [comment]
Thank *you*, you're the one who came up with and maintains this whole project :)

I would like to get rid of that delegator call if possible, I might have a go at that this evening.

**Pull request merged**
