### PR TITLE
Fix `UnicodeEncodeError` in help.py

### PR DESCRIPTION
**Pull request by maxkrivich**
I don't know why but on MacOS  when you execute this command `python -m pipenv.help` and redirect output stream to some another file, script fails with exception. 

```bash
$ python -m pipenv.help > test.txt 
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/maxkrivich/Projects/pipenv/pipenv/help.py", line 89, in <module>
    main()
  File "/Users/maxkrivich/Projects/pipenv/pipenv/help.py", line 48, in main
    print(u'Pipenv–specific environment variables:')
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 6: ordinal not in range(128)
```

### CODE REVIEW

**Comment by techalchemy** [comment]
Thanks for the pr (again)

I wonder if this works on windows... will test when I get home

**Comment by maxkrivich** [comment]
@techalchemy I'm not sure what it is reproducible on windows.

**Comment by techalchemy** [comment]
Yeah just want to make sure that the explicit encoding doesn't break anything in the console, checking now

**Comment by techalchemy** [comment]
works ok for me, thanks for the fix!

**Pull request merged**
