### PR TITLE
Assume that vcs and direct URL installs need to be reinstalled

### PR DESCRIPTION
**Pull request by matteius**
Thank you for contributing to Pipenv!

### The issue

Fixes issue #5791 

### The fix

Since skip-lock is still in play, and the existing method is operating off only the install req, we cannot with certainty know if the remote requirement has been updated, so queue it for install by pip.

### The checklist

* [X] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Review by oz123 — APPROVED** [review]

**Comment by oz123** [comment]
@matteius The change is OK. But does it really fix the issue? Reading the issue (briefly) it seems there is still work going on? Can this be merged?

**Comment by fmssn** [comment]
Possibly 
```python
return(
    if req.link is not None and
    ...
)
```

Would also be ok. The change is pretty important, e.g. it atm crashes the current prefect installation at python 3.11.

**Comment by matteius** [comment]
@fmssn Sorry but I don't understand what you mean by its crashing on a perfectly good install of 3.11 or how this change could affect that.

@oz123 Yeah I am not sure yet why this change wouldn't have solved their issue but probably needs more discovery and possibly this change isn't quite it yet.

**Comment by fmssn** [comment]
@matteius 

For reproduction, you can open a dev container with e.g. "prefecthq/prefect:2.13-python3.11". 

With Pipfile

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
prefect = "*"

[dev-packages]
pytest = "*"
```
Executing
```sh
pipenv lock 
pipenv install --system
```

yields 
`AttributeError: 'NoneType' object has no attribute 'scheme'`

This is because req.link is optional and of Type `InstallRequirement`, with the default being None. Therefore accessing the attribute scheme if it is `None` raises an Attribute Error.

**Pull request merged**
