### PR TITLE
Warning for non-existent PIPENV_DOTENV_LOCATION file

### PR DESCRIPTION
**Pull request by orn688**
##### The issue

Addresses #2754.

##### The fix

This displays a warning if the `PIPENV_DOTENV_LOCATION` environment variable is set but the file specified does not exist.

##### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by orn688** [comment]
I noticed there don't seem to be any tests for the `PIPENV_DOTENV_LOCATION` feature – would a couple tests in `tests/unit/test_core.py` be accepted as part of this PR?

**Comment by techalchemy** [comment]
That would certainly be welcome (we have been heavily focused on a few resolver-related projects we are trying to incorporate into pipenv so we haven't been putting a lot of attention on this, so apologies for the slowness)

**Comment by techalchemy** [comment]
Failure logs:

```
_____________ test_load_dot_env_from_environment_variable_location _____________
[gw0] linux2 -- Python 2.7.15 /root/.local/share/virtualenvs/pipenv-SHwetwt5-2.7/bin/python2.7
 
capsys = <_pytest.capture.CaptureFixture object at 0x7f3e6e950f10>
 
    @pytest.mark.core
    def test_load_dot_env_from_environment_variable_location(capsys):
>       with temp_environ(), TemporaryDirectory(prefix='pipenv-') as tempdir:
 
tests/unit/test_core.py:24:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pipenv/_compat.py:102: in __init__
    self.name = mkdtemp(suffix, prefix, dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
suffix = None, prefix = 'pipenv-', dir = '/tmp'
 
    def mkdtemp(suffix="", prefix=template, dir=None):
        """User-callable function to create and return a unique temporary
        directory.  The return value is the pathname of the directory.
    
        Arguments are as for mkstemp, except that the 'text' argument is
        not accepted.
    
        The directory is readable, writable, and searchable only by the
        creating user.
    
        Caller is responsible for deleting the directory when done with it.
        """
    
        if dir is None:
            dir = gettempdir()
    
        names = _get_candidate_names()
    
        for seq in xrange(TMP_MAX):
            name = names.next()
>           file = _os.path.join(dir, prefix + name + suffix)
E           TypeError: cannot concatenate 'str' and 'NoneType' objects
 
/usr/lib/python2.7/tempfile.py:337: TypeError
_____________________ test_doesnt_load_dot_env_if_disabled _____________________
[gw0] linux2 -- Python 2.7.15 /root/.local/share/virtualenvs/pipenv-SHwetwt5-2.7/bin/python2.7
 
capsys = <_pytest.capture.CaptureFixture object at 0x7f3e6e960990>
 
    @pytest.mark.core
    def test_doesnt_load_dot_env_if_disabled(capsys):
>       with temp_environ(), TemporaryDirectory(prefix='pipenv-') as tempdir:
 
tests/unit/test_core.py:37:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pipenv/_compat.py:102: in __init__
    self.name = mkdtemp(suffix, prefix, dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
suffix = None, prefix = 'pipenv-', dir = '/tmp'
 
    def mkdtemp(suffix="", prefix=template, dir=None):
        """User-callable function to create and return a unique temporary
        directory.  The return value is the pathname of the directory.
    
        Arguments are as for mkstemp, except that the 'text' argument is
        not accepted.
    
        The directory is readable, writable, and searchable only by the
        creating user.
    
        Caller is responsible for deleting the directory when done with it.
        """
    
        if dir is None:
            dir = gettempdir()
    
        names = _get_candidate_names()
    
        for seq in xrange(TMP_MAX):
            name = names.next()
>           file = _os.path.join(dir, prefix + name + suffix)
E           TypeError: cannot concatenate 'str' and 'NoneType' objects
 
/usr/lib/python2.7/tempfile.py:337: TypeError
_________________ test_load_dot_env_warns_if_file_doesnt_exist _________________
[gw0] linux2 -- Python 2.7.15 /root/.local/share/virtualenvs/pipenv-SHwetwt5-2.7/bin/python2.7
 
capsys = <_pytest.capture.CaptureFixture object at 0x7f3e6e950d90>
 
    @pytest.mark.core
    def test_load_dot_env_warns_if_file_doesnt_exist(capsys):
>       with temp_environ(), TemporaryDirectory(prefix='pipenv-') as tempdir:
 
tests/unit/test_core.py:54:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
pipenv/_compat.py:102: in __init__
    self.name = mkdtemp(suffix, prefix, dir)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 
suffix = None, prefix = 'pipenv-', dir = '/tmp'
 
    def mkdtemp(suffix="", prefix=template, dir=None):
        """User-callable function to create and return a unique temporary
        directory.  The return value is the pathname of the directory.
    
        Arguments are as for mkstemp, except that the 'text' argument is
        not accepted.
    
        The directory is readable, writable, and searchable only by the
        creating user.
    
        Caller is responsible for deleting the directory when done with it.
        """
    
        if dir is None:
            dir = gettempdir()
    
        names = _get_candidate_names()
    
        for seq in xrange(TMP_MAX):
            name = names.next()
>           file = _os.path.join(dir, prefix + name + suffix)
E           TypeError: cannot concatenate 'str' and 'NoneType' objects
 
/usr/lib/python2.7/tempfile.py:337: TypeError
```

**Comment by orn688** [comment]
@techalchemy Thanks, fixed! It's all done now – the tests I added are somewhat integration-y but I figured `test_core.py` was a better place for them since they directly test the `load_dot_env` function.

**Comment by techalchemy** [comment]
Thanks for the incredibly thorough testing, this PR looks very good to me and i think it's super helpful. Much appreciated

**Pull request merged**
