### PR TITLE
Update core.py

### PR DESCRIPTION
**Pull request by Cologler**
for #3694

### CODE REVIEW

**Comment by frostming** [comment]
IMO the error message is not so clear and needs to be capitalized. The same message as `pipenv --venv` should be just OK.

**Comment by Cologler** [comment]
@frostming "location not created nor specified" was copied from current RuntimeError. This won't make break changes if some tools captured stderr and search the string.

**Comment by erinxocon** [comment]
@Cologler Thanks for contributing to pipenv!  It will be nice to not have the whole stack trace print out.  I hope that I can work on the cause of the underlying problem so we won't have to see the error message 😅

**Comment by Cologler** [comment]
@frostming any news for this?

**Comment by frostming** [comment]
would you mind adding a news entry?

**Comment by Cologler** [comment]
@frostming My English is poor 😂

**Pull request merged**
