### PR TITLE
Update vendored dependencies, relevant API usage, and CI config

### PR DESCRIPTION
**Pull request by techalchemy**
Update vendored dependencies and invocations

- Update vendored and patched dependencies
  - Update patches on `piptools`, `pip`, `pip-shims`, `tomlkit`
- Fix invocations of dependencies
  - Fix custom `InstallCommand` instantiation
  - Update `PackageFinder` usage
  - Fix `Bool` stringify attempts from `tomlkit`

Updated vendored dependencies:
  - **attrs**: ``18.2.0`` => ``19.1.0``
  - **certifi**: ``2018.10.15`` => ``2019.3.9``
  - **cached_property**: ``1.4.3`` => ``1.5.1``
  - **cerberus**: ``1.2.0`` => ``1.3.1``
  - **click**: ``7.0.0`` => ``7.1.1``
  - **click-completion**: ``0.5.0`` => ``0.5.1``
  - **colorama**: ``0.3.9`` => ``0.4.3``
  - **contextlib2**: ``(new)`` => ``0.6.0.post1``
  - **distlib**: ``0.2.8`` => ``0.2.9``
  - **funcsigs**: ``(new)`` => ``1.0.2``
  - **importlib_metadata** ``1.3.0`` => ``1.5.1``
  - **importlib-resources**:  ``(new)`` => ``1.4.0``
  - **idna**: ``2.7`` => ``2.9``
  - **jinja2**: ``2.10.0`` => ``2.11.1``
  - **markupsafe**: ``1.0`` => ``1.1.1``
  - **more-itertools**: ``(new)`` => ``5.0.0``
  - **orderedmultidict**: ``(new)`` => ``1.0``
  - **packaging**: ``18.0`` => ``19.0``
  - **parse**: ``1.9.0`` => ``1.15.0``
  - **pathlib2**: ``2.3.2`` => ``2.3.3``
  - **pep517**: ``(new)`` => ``0.5.0``
  - **pexpect**: ``4.6.0`` => ``4.8.0``
  - **pip-shims**: ``0.2.0`` => ``0.5.1``
  - **pipdeptree**: ``0.13.0`` => ``0.13.2``
  - **pyparsing**: ``2.2.2`` => ``2.4.6``
  - **python-dotenv**: ``0.9.1`` => ``0.10.2``
  - **pythonfinder**: ``1.1.10`` => ``1.2.2``
  - **pytoml**: ``(new)`` => ``0.1.20``
  - **requests**: ``2.20.1`` => ``2.23.0``
  - **requirementslib**: ``1.3.3`` => ``1.5.4``
  - **scandir**: ``1.9.0`` => ``1.10.0``
  - **shellingham**: ``1.2.7`` => ``1.3.2``
  - **six**: ``1.11.0`` => ``1.14.0``
  - **tomlkit**: ``0.5.2`` => ``0.5.11``
  - **urllib3**: ``1.24`` => ``1.25.8``
  - **vistir**: ``0.3.0`` => ``0.5.0``
  - **yaspin**: ``0.14.0`` => ``0.14.3``
  - **zipp**: ``0.6.0``

- Removed vendored dependency **cursor**.

### CODE REVIEW

**Comment by brainwane** [comment]
btw @davidstaheli do you have any time to help us wrangle Azure pipelines? We're having a problem here https://dev.azure.com/pypa/pipenv/_build/results?buildId=21032&view=logs&j=89390fe7-33d2-53e5-d9b1-9b3b600e8bb2&t=154e6688-01f7-599c-c8c6-29bc92fc1d2f where it's unclear whether the "Run integration tests" step is kicking off at all.

**Comment by brainwane** [comment]
Fun fact: Azure jobs [time out](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?view=azure-devops&tabs=yaml#timeouts) and [sometimes that is confusing](https://github.com/MicrosoftDocs/vsts-docs/issues/4342).

According to [the past-180-days failure report](https://dev.azure.com/pypa/pipenv/_pipeline/analytics/stageawareoutcome?definitionId=16&contextType=build) pipenv's builds started failing between 2020-01-10 and 2020-01-12 -- we can't see those builds because they are over 30 days old, but we suspect that, at some point there, some runs went over the 60 minute mark and thus things started failing ([example](https://github.com/pypa/pipenv/runs/386326682)).

So this PR is still in progress as Dan splits up the tests so each one takes under 60 minutes. ([IRC log.](http://kafka.dcpython.org/day/pypa-dev/2020-04-01)) If you want to help, [you can join us in IRC, #pypa-dev on Freenode,](https://webchat.freenode.net/?channels=%23pypa-dev) or comment here with tips.

**Comment by brainwane** [comment]
From [IRC](http://kafka.dcpython.org/day/pypa-dev/) in the past few days:

> windows failures don't appear in azure test results
> the builds fail but nothing indicates what went wrong 
> https://dev.azure.com/pypa/pipenv/_build/results?buildId=21643&view=results why doesn't windows report its failures :|
> it fails but reports nothing

Dan has tried runing a subset of the tests in the CI and that didn't help. Azure and Windows testing experts: please help.

**Comment by pietrodn** [comment]
If you click on "Run integration tests" it is impossible to get to the actual test report. However if you click on the name of the test environment, such as "TestWindows Python38", you are shown the link "93,6% tests passed": if you click on it, you get the actual outcome of the tests.

I'll include an image to be more clear.
image

Here's the failure: [log](https://dev.azure.com/pypa/pipenv/_build/results?buildId=21643&view=ms.vss-test-web.build-test-results-tab&runId=1338198&resultId=100058&paneView=debug), [code](https://github.com/pypa/pipenv/blob/bfbe1304f63372a0eb7c1531590b51195db453ea/tests/integration/test_install_markers.py#L129-L151)

**Comment by brainwane** [comment]
@pradyunsg [also started poking at this problem in a branch](https://github.com/pradyunsg/pipenv/tree/ci/experiments).

**Comment by pfmoore** [comment]
Has anyone run the tests on a local Windows PC, rather than on CI? I run Windows, so if it helps I can test locally for you. I find Azure pipelines a bit of a black art, though, so I can't help much there if it's Azure-specific 🙁

**Comment by techalchemy** [comment]
Thanks @pietrodn I'm able to see that bit, and I'm able to see the fact that tests are exiting with error code `1`, but that isn't particularly useful unless I can see what actually is going wrong.  I have spun up multiple windows images to test against and can't replicate any failures anymore since removing `pytest-timeout` so I really don't know what's going wrong.

Separately, python 3.6 seems to fail exclusively on linux, exclusively in CI -- I can't reproduce that failure in any environment when I run tests myself. 

I did just work out how to stop github from canceling CI on failure, and that seems to have worked out ok.

@pfmoore I have run them on a windows instance on GCE and everything passes.  in github CI the only failure seems to be related to windows long paths (is this a pip bug?)

```console
[pipenv.exceptions.InstallError]: Traceback (most recent call last):
[pipenv.exceptions.InstallError]:   File "c:\users\runneradmin\appdata\local\temp\pipenv-l0mqj714-project\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 186, in _main
[pipenv.exceptions.InstallError]:     status = self.run(options, args)
[pipenv.exceptions.InstallError]:   File "c:\users\runneradmin\appdata\local\temp\pipenv-l0mqj714-project\.venv\lib\site-packages\pip\_internal\commands\install.py", line 395, in run
[pipenv.exceptions.InstallError]:     installed = install_given_reqs(
[pipenv.exceptions.InstallError]:   File "c:\users\runneradmin\appdata\local\temp\pipenv-l0mqj714-project\.venv\lib\site-packages\pip\_internal\req\__init__.py", line 63, in install_given_reqs
[pipenv.exceptions.InstallError]:     uninstalled_pathset = requirement.uninstall(
[pipenv.exceptions.InstallError]:   File "c:\users\runneradmin\appdata\local\temp\pipenv-l0mqj714-project\.venv\lib\site-packages\pip\_internal\req\req_install.py", line 686, in uninstall
[pipenv.exceptions.InstallError]:     uninstalled_pathset = UninstallPathSet.from_dist(dist)
[pipenv.exceptions.InstallError]:   File "c:\users\runneradmin\appdata\local\temp\pipenv-l0mqj714-project\.venv\lib\site-packages\pip\_internal\req\req_uninstall.py", line 542, in from_dist
[pipenv.exceptions.InstallError]:     assert (link_pointer == dist.location), (
[pipenv.exceptions.InstallError]: AssertionError: Egg-link c:\users\runner~1\appdata\local\temp\pipenv-1xuerp3g-test\requests does not match installed location of requests (at c:\users\runneradmin\appdata\local\temp\pipenv-1xuerp3g-test\requests)
```

**Comment by pietrodn** [comment]
>  I'm able to see the fact that tests are exiting with error code 1, but that isn't particularly useful unless I can see what actually is going wrong.

@techalchemy actually here ([link](https://dev.azure.com/pypa/pipenv/_build/results?buildId=21643&view=ms.vss-test-web.build-test-results-tab&runId=1338198&resultId=100058&paneView=debug)) you can see the specific assertion that fails:

```python
assert yarl['markers'] in ["python_version in '3.4, 3.5, 3.6'", "python_version >= '3.4'"]
```

in `test_resolver_unique_markers`.

The latest commits broke the Azure build (syntax error on the config, [see log](https://github.com/pypa/pipenv/pull/4169/checks?check_run_id=575021735)), so those tests aren't running anymore.

**Comment by techalchemy** [comment]
@pietrodn I'm familiar with that one. I am focused on the windows failures at the moment, that test fails only on linux on python 3.6.

**Comment by pietrodn** [comment]
Ah, sorry... the Azure interface tricked me. Even if I clicked on the Windows built, it kept showing the same error on Linux. The interface is _really_ counter-intuitive. 😕

**Comment by pietrodn** [comment]
Let's give another shot at it. [This StackOverflow issue](https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide/) describes our problem. It basically says that PowerShell cannot handle correctly stderr under certain conditions.

The solution should be to run pytest like this:

```
pipenv run pytest -ra -n 4 --junit-xml=junit/test-results.xml tests/ 2>&1 | %{ "$_" }
```

where the `2>&1 | %{ "$_" }` redirects stderr to stdout.

**Comment by techalchemy** [comment]
> The solution should be to run pytest like this:

@pradyunsg tried that in a test commit on a separate branch he was experimenting with, but didn't have any success that I could see anyway

**Comment by frostming** [comment]
I searched through `vcrpy`'s historic releases and didn't find one that matches the requirement of test case `test_resolver_unique_markers`, maybe it was yanked.

We should either fake a package with duplicate markers or directly remove that case.

**Comment by techalchemy** [comment]
> I searched through vcrpy's historic releases and didn't find one that matches the requirement of test case test_resolver_unique_markers, maybe it was yanked.

https://pypi.org/project/vcrpy/2.0.1/#files or https://pypi.org/pypi/vcrpy/2.0.1/json seem to show up ok for me -- and when I parse the wheel as I am now doing here: https://github.com/pypa/pipenv/blob/feature/vendor-update/tests/pytest-pypi/pytest_pypi/app.py#L92 I do find the expected markers in `yarl`.

I had a suspicion that this was an issue related to us not including `data-requires-python` in our generated html, but that seems to be wrong... I have absolutely no clue what is going on here...

**Comment by frostming** [comment]
> https://pypi.org/project/vcrpy/2.0.1/#files or https://pypi.org/pypi/vcrpy/2.0.1/json seem to show up ok for me -- and when I parse the wheel as I am now doing here: 

I mean `yarl` requirement doesn't have duplicate markers, which is the purpose of the test case.
And `yarl 1.2.0` has `"requires_python": ">=3.5.3"`, which is where the test output comes from. The resolver may have some marker merging logic.

**Comment by ncoghlan** [comment]
@techalchemy Given that the CI on this branch seems to be in a much better state than the CI on master, perhaps it would make sense to go ahead and merge this, and then make a smaller PR that just focuses on the Windows CI fixes?

At the moment, I'm hesitant to look at other possible CI improvements (like #4185), as I know this change is still incoming.

**Comment by pradyunsg** [comment]
Notes from my late-at-night experiments yesterday:

- the no-test-outputs issue happens even with --collect-only passed to pytest (the tests don't need to run to exhibit the underlying issue here). The CI run still takes ~8 minutes but that's a lot better than 30+ minutes or 1 hour, which is useful since I'm laser focused on figuring out what's up with Windows on AP (which is our current blocker).

- not running the tests by removing the pipenv run command entirely, makes the issue go away (so... `pipenv run pytest ...` is what's causing the failures).

- guess on why the stackoverflow solution doesn't solve our problem: AP runs the entire thing in a powershell script (that's generated based on the YAML) and we'd want to add the redirect logic at that level? 🤷🏻‍♂️

I'll spend some more time in this today. My current thoughts are:

- try running pytest directly.
  - tells us if the issue is with pytest or something else.
- try running pipenv run \<something simple>
  - tells us if the issue is with pipenv.
- try using cmd for the test run, instead of powershell, which might work around the encoding issue we're seemingly hitting.

A good place to look at my experiments as they proceed would be https://github.com/pradyunsg/pipenv/pulls/1, since all the commits and GitHub Checks reports would be accessible directly. Fair warning: my commit messages get useless quickly if I'm getting frustrated at CI. :)

**Comment by pradyunsg** [comment]
Good news!

> try using cmd for the test run, instead of powershell, which might work around the encoding issue we're seemingly hitting.

Tried it with `--collect-only` and [it worked](https://github.com/pradyunsg/pipenv/pull/1#issuecomment-611994725)! I'm running the full test suite run now, and that seems to be [working](https://dev.azure.com/pradyunsg-azure/pipenv/_build/results?buildId=515&view=logs&j=2d4cb656-6149-5a33-f8b2-fd60a79c32e2) as well! ^>^

**Comment by techalchemy** [comment]
> > [pypi.org/project/vcrpy/2.0.1/#files](https://pypi.org/project/vcrpy/2.0.1/#files) or [pypi.org/pypi/vcrpy/2.0.1/json](https://pypi.org/pypi/vcrpy/2.0.1/json) seem to show up ok for me -- and when I parse the wheel as I am now doing here:
> 
> I mean `yarl` requirement doesn't have duplicate markers, which is the purpose of the test case.
> And `yarl 1.2.0` has `"requires_python": ">=3.5.3"`, which is where the test output comes from. The resolver may have some marker merging logic.

The issue here wasn't that the requirement itself had duplicate markers, but that pipenv was locking with duplicate markers. In either case the test also checks that we *retain* the marker for the python version if its present (which we do want to do).

**Pull request merged**
