### PR TITLE
Add instructions for conda plus pipenv

### PR DESCRIPTION
**Pull request by jtratner**
Figured it'd be a good idea to have a standard answer for "How do I use this with conda?"

Left out any commentary about conflicts between conda and Pipenv about requirements... hoping that's obvious to folks who'd use both.

### CODE REVIEW

**Comment by kennethreitz** [comment]
this is not how i'd recommend using conda and pipenv together.

**Comment by jtratner** [comment]
gotcha - do you have a recommended way of doing it?

Maybe:

```
source activate myenvironment
pipenv install --python=$(which python)
```

would be helpful to know / have a recommended way to handle - actively exploring using pipenv + conda at work right now.

**Comment by kennethreitz** [comment]
that second one, without the source activate part :)

**Comment by jtratner** [comment]
@kennethreitz - ptal

**Pull request merged**
