### PR TITLE
Prep for warehouse release (ETA: EOM)

### PR DESCRIPTION
**Pull request by kennethreitz**
This pull request changes the defaults for PyPI, for when the URL officially changes later this month.

### CODE REVIEW

**Comment by uranusjr** [comment]
Maybe also a good idea to detect the old URL from previously generated Pipfile, and print a courtesy note to prompt the user to switch?

**Comment by kennethreitz** [comment]
The old version will continue to work for a long time.

**Comment by uranusjr** [comment]
It seems pypi.org has left beta.

**Comment by techalchemy** [comment]
@auvipy we will merge it, but there is no rush

**Pull request merged**
