### PR TITLE
add PIPENV_SKIP_LOCK envvar, and suitable doc

### PR DESCRIPTION
**Pull request by devxpy**
Fixes https://github.com/pypa/pipenv/issues/2200.

[🐍🏕️](http://www.pycampers.com/)

### CODE REVIEW

**Comment by techalchemy** [comment]
As I said in the issue, isn’t this covered already by our use of `auto_envvar_prefix`?

**Comment by devxpy** [comment]
@techalchemy. I am not sure, can you please tell me the env var to set, so that I can test it out myself?

**Comment by devxpy** [comment]
Weird, search results don't seem to show any mention of `auto_envvar_prefix`

https://github.com/pypa/pipenv/search?q=auto_envvar_prefix&unscoped_q=auto_envvar_prefix

What am I missing here?

**Comment by techalchemy** [comment]
The option I was looking for relates to [this approved enhancement proposal](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-002.md) which describes the implementation we plan to adopt which uses click's `auto_envvar_prefix` option which you can read about [in click's documentation](https://click.palletsprojects.com/en/7.x/options/#values-from-environment-variables).  I'd prefer to see a refactor in that direction than to keep adding environment variables that are manually defined and maintained.

**Comment by techalchemy** [comment]
Seems like that option includes the command name in between, i.e. `PIPENV_LOCK_SKIP_LOCK` in order to work, so I'll include this

**Comment by devxpy** [comment]
@techalchemy, Okay will merge master

**Comment by techalchemy** [comment]
I merged your branch into the one I have queued up to merge already

**Pull request closed without merging**
