### PR TITLE
Remove --dev option for uninstall

### PR DESCRIPTION
**Pull request by jxltom**
### The issue

I think ```pipenv uninstall --dev``` is not working currently. We should either support it or remove it from the CLI.

Discussions are welcomed :)

### The fix

A options group ```lock_base_options``` is introduced, which can also be used in ```lock_options``` instead of current ```install_base_options``` since ```--dev``` is actually also not supported in ```pipenv lock```. But it is another PEEP for that, which I'm going to propose later

### The checklist

* [ ] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by jxltom** [comment]
I checked ```test_uninstall.py``` again, it doesn't have any tests related with ```uninstall --dev```

As for the saying that it's not working, if I understand correctly, ```uninstall``` method below doesn't take ```state.installstate.dev``` as an argument at all.

https://github.com/pypa/pipenv/blob/master/pipenv/cli/command.py#L287-L300

So I don't think ```pipenv uninstall --dev``` is working. User can pass ```--dev``` to ```uninstall```, but it won't take any effect.

**Comment by techalchemy** [comment]
You’re right, but I can’t imagine any justification for this at all...

**Comment by jxltom** [comment]
@techalchemy So that means ```pipenv unisntall --dev``` should be supported?

Just for clafication, as the below Pipfile, ```pipenv uninstall flask``` should uninstall flask and only remove it from ```dev-packages``` part, right?

```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[packages]
flask = "*"

[dev-packages]
flask = "*"

[requires]
python_version = "2.7"
```

**Comment by jxltom** [comment]
Closed and track this in https://github.com/pypa/pipenv/issues/3385

**Pull request closed without merging**
