### PR TITLE
Split tests

### PR DESCRIPTION
**Pull request by uranusjr**
As promised, split tests into modules. I add some Pytest hooks to perform cross-module setup of environs, and implement `needs_internet` as a marker instead so it can be used in multiple files.

Similarly, `PipenvInstance` is wrapped in a fixture so we can simply name it in the arguments.

🤞

### CODE REVIEW

**Comment by uranusjr** [comment]
Asteroid seems stuck. Any objections on this? I want to merge if possible because this would cause conflicts to all new test contributions.

**Comment by techalchemy** [comment]
gotta give me a chance to review :p

**Comment by uranusjr** [comment]
Sure, go head 😄 I’ll leave this to you then.

**Comment by techalchemy** [comment]
seems fine at a glance, probably want to organize it in a fundamentally different way at some point but that's another project imo... if you can confirm you didn't remove any tests i'd say just hit the button when you're ready, I'll review more carefully later

**Comment by uranusjr** [comment]
No tests removed I promise. I actually un-skipped one because it’s working.

**Pull request merged**
