### PR TITLE
WIP: Remove duplicate vendored libs

### PR DESCRIPTION
**Pull request by oz123**
As discussed in #5174 we move towards using pip's own vendored versions.

I am going to remove all the packages, each one in a separate commit, and in beween I am running the tests locally.
Hence, this will take a few days to finish.

### CODE REVIEW

**Comment by matteius** [comment]
Can you add these to the `LIBRARY_RENAMES` in the vendoring script: https://github.com/pypa/pipenv/blob/main/tasks/vendoring/__init__.py#L59

**Comment by oz123** [comment]
> Can you add these to the `LIBRARY_RENAMES` in the vendoring script: https://github.com/pypa/pipenv/blob/main/tasks/vendoring/__init__.py#L59

It's already done. Otherwise, it's impossible to run the vendoring task.
https://github.com/pypa/pipenv/blob/9409f3786acace09b5843c3918e2cd346d5f21c2/tasks/vendoring/__init__.py#L64

**Comment by matteius** [comment]
>It's already done.

Not sure why I didn't see that in there, but sure enough.

**Comment by oz123** [comment]
Closing this in favour of #5215. This got too much. We'll have to remove duplicates in a slow manner along a few releases.

**Pull request closed without merging**
