### PR TITLE
chore : refactor code quality issues

### PR DESCRIPTION
**Pull request by ankitdobhal**
## Description
Hey 👋 , I'm member of the Developer Outreach team at DeepSource and ran DeepSource analysis on my fork of the repo. It found some interesting [code quality improvements](https://deepsource.io/gh/ankitdobhal/pipenv/issues) to consider.

This PR fixes a few of the issues detected for you to assess if it is right for you.
Happy to provide the tweaks separately otherwise :)

### What problem does this PR solve?

This PR improve some code quality issues like anti-pattern and bug risks. 

### The fix

- Remove `unused` imports
- Remove `duplicate` dictionary key(s)
- Refactor the comparison involving `not`
- Remove `length check` in favour of truthiness of the object
- Added `.deepsource.toml` file for continuous analysis on bug risks/performance/code-quality issues on new changes.

### CODE REVIEW

**Comment by uranusjr** [comment]
I think Pipenv still supports Python 2 so at least all the `object` removals shouldn’t be there.

**Comment by ankitdobhal** [comment]
> I think Pipenv still supports Python 2 so at least all the `object` removals shouldn’t be there.

Hey , @uranusjr I have updated the PR.

**Review by uranusjr — APPROVED** [review]

**Comment by ankitdobhal** [comment]
@uranusjr Thanks for approving the changes, kindly take a look to merge the fixes.

**Comment by frostming** [comment]
Thanks for contributing

**Pull request merged**
