### PR TITLE
Allow environment variable references to be passed through to the Pipfile unredacted

### LINKED ISSUE #2635: Import Private Github Repo via Environment Variables
You can use `pip` to pull a private Github repo using environment variables. 

```
# requirements.txt
git+https://${AUTH_USER}:${AUTH_PASSWORD}@github.com/user/myproject.git@1.2.3#egg=myproject
```

Then run

```
> pip install -r requirements.txt
```

Is there a way to do this with Pipenv? I tried using the environment variable method described [here](https://docs.pipenv.org/advanced/#injecting-credentials-into-pipfiles-via-environment-variables), but it looks like it's not the right approach.

```
Could not find a version that matches myproject (from -r /var/folders/6r/719kpmn511l0ghtx4v1rbxdm0000gn/T/pipenv-5xvfp5mw-requirements/pipenv-wm4ivcah-constraints.txt (line 11))
No versions found
Were https://pypi.python.org/simple or git+https://${AUTH_USER}:${AUTH_PASSWORD}@github.com/user/myproject.git#egg=myproject reachable?
```

<details><summary>$ pipenv --support</summary>

Pipenv version: `'2018.7.1'`

Pipenv location: `'/usr/local/lib/python2.7/site-packages/pipenv'`

Python location: `'/usr/local/opt/python@2/bin/python2.7'`

Other Python installations in `PATH`:

  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/local/bin/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`

  - `2.7.14`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/usr/local/bin/python2`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '0',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '17.6.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64',
 'python_full_version': '2.7.14',
 'python_version': '2.7',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `AUTH_USER`
  - `AUTH_PASSWORD`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/Users/juansc/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:/Users/juansc/git/go/bin`
  - `SHELL`: `/bin/zsh`
  - `LANG`: `en_US.UTF-8`
  - `PWD`: `/Users/juansc/git/project/`

---------------------------

Contents of `Pipfile` ('/Users/juansc/git/project/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[[source]]
url = "git+https://${AUTH_USER}:${AUTH_PASSWORD}@github.com/user/myproject.git#egg=myproject"
verify_ssl = true
name = "myproject-name"

[packages]
myproject = {'ref'='1.2.3', index="myproject-name"}

[requires]
python_version = "3.6"

```

Contents of `Pipfile.lock` ('/Users/juansc/git/project/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "c4290d9b83dd0d70dc2972be0caa2eb452670ce057ca3b973290f5b618020783"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.6"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            },
            {
                "name": "myproject-name",
                "url": "git+https://${AUTH_USER}:${AUTH_PASSWORD}@github.com/user/myproject.git#egg=myproject",
                "verify_ssl": true
            }
        ]
    },
    "default": {
    }
}

```
</details>

### PR DESCRIPTION
**Pull request by matteius**
Fixes #2635

### CODE REVIEW

**Comment by matteius** [comment]
I'll add a news fragment before merging once this gets reviewed.

**Review by oz123 — CHANGES_REQUESTED** [review]
The string method of `package.link` should redact the authentication according to the code here:
https://github.com/pypa/pip/blob/65680b4bb1a2412e97bc90e49df6999b5f362e40/src/pip/_internal/models/link.py#L93

I suspect the f-string (which calls the  __repr__ ) should be also using the string method explicitly.

In other words: `package.link` should not show auth information.

**Comment by matteius** [comment]
@oz123 That is the problem -- people are using environment variables for the auth and they get redacted.

**Comment by oz123** [comment]
I still don't understand what issue is being fixed here.

We should not leak authentication information to Pipefile or Pipefile.lock.

If this PR allows this, we can expect people to open a CVE for this.

**Comment by oz123** [comment]
> @oz123 That is the problem -- people are using environment variables for the auth and they get redacted.

Redacted from where? From the Pipefile? That's great, pipenv does its job. 
If they get redacted from the files pipenv is writing while trying to install a package, then the fix should be some where else.

**Comment by matteius** [comment]
@oz123 For the case where the user is using environment variables, they don't get expanded, but they do get redacted, which means this doesn't work:

```
# requirements.txt
git+https://${AUTH_USER}:${AUTH_PASSWORD}@github.com/user/myproject.git@1.2.3#egg=myproject

Then run

> pip install -r requirements.txt
```

Becasue str(package.link) will redact it to be `git+https://${AUTH_USER}:****@github.com/user/myproject.git@1.2.3#egg=myproject`

If you have just a user variable, like this:  `git+https://${AUTH_USER}@github.com/user/myproject.git@1.2.3#egg=myproject`
Then that variable will get redacted as well:
`git+https://****@github.com/user/myproject.git@1.2.3#egg=myproject`

Which creates a not lockable or installable Pipfile.   The ask of https://github.com/pypa/pipenv/issues/2635 is to fix this -- but you are probably correct as well, we need a way to detect if they are environment variables, to not redact them.

**Comment by oz123** [comment]
OK, I see where is the problem.

These are not environment variables, rather references to them. So if someone was smart and didn't specify the password, pip's own code still think it's a password.

Using `_url` can be dangerous, we could use [split_auth_from_netloc](
https://github.com/pypa/pip/blob/0d4e9eb72253c008f2790482e664ce92198c5240/src/pip/_internal/utils/misc.py#L427) from pip to check for a password or a variable and do something about it.

Something could be:

1. Warn the user.
2. Redact if it is a password
3. Pass it on to Pipfile if the password is the known form for a variable reference, e.g. `${PASSWORD}` or `${password}` or in regex: `${\w+}`.

**Comment by matteius** [comment]
Changes made to address the concerns and tests added for the various cases.

**Comment by matteius** [comment]
@oz123 this PR is insightful, because mac os failed on every test pips_to_dep tests regarding requests, possibly because of my new Pipfile tests?  I noticed a weird behavior on my mac this past week that took me a while to track down -- even if there is no virtualenv, if there is a Pipfile in a higher level directory, then pipenv prefers to use that over the Pipfile in your current working directory, at least on a mac.

**Review by oz123 — CHANGES_REQUESTED** [review]

**Review by oz123 — APPROVED** [review]

**Pull request merged**
