### PR TITLE
Remove old way of generting requirements.

### PR DESCRIPTION
**Pull request by matteius**
Thank you for contributing to Pipenv!

### The issue

Remove the deprecated `install -r` command and simplify the CLI interface + logic.

Fixes: #5198

### The fix

We have the `pipenv requirements` command now.

### The checklist

* [X] Associated issue
* [X] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Review by oz123 — APPROVED** [review]

**Comment by EugeniuZ** [comment]
`pipenv lock -r` does variable substitution (as of 2022.8.5) while `pipenv requirements` does not. This is needed when including private pypi repos with credentials that are substituted by env variables.

**Comment by oz123** [comment]
Can you please open a separate issue for that?

**Comment by EugeniuZ** [comment]
#5033 and #5200 seem to be related

**Comment by matteius** [comment]
@EugeniuZ Its actually #5272  -- 5033 should probably be closed (people were getting hung up on index restricted packages) and 5200 is this PR.

**Pull request merged**
