### PR TITLE
Fix verbose display

### PR DESCRIPTION
**Pull request by intrinseca**
In investigating #1552 I thought I'd try and put in a proper fix - this way the verbose output is printed whether there is an error or not, and I also traced back the `verbose` flag being dropped up the call stack.

### CODE REVIEW

**Comment by kr-mercury** [comment]
Can one of the admins verify this patch?

**Comment by kr-mercury** [comment]
Can one of the admins verify this patch?

**Comment by kennethreitz** [comment]
@kr-mercury build

**Comment by kr-mercury** [comment]
Can one of the admins verify this patch?

**Pull request merged**
