### PR TITLE
Add --bare behavior to sync and clean

### PR DESCRIPTION
**Pull request by jcrotts**
Implement some behavior for --bare in sync and clean, and add bare an option to do_clean in cli.py

### The issue

https://github.com/pypa/pipenv/issues/3041

### The fix

Added logic for --bare to sync and clean since they are passed in as arguments. 
Excluding error messages.

Also added --bare as a click option to clean.

### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by uranusjr** [comment]
I only see it be added to `clean`? Also, a news fragment to describe the change would be nice.

**Comment by jcrotts** [comment]
--bare was an option for sync already in command.py, but I don't think it actually did anything.

Sure thing I'll add a fragment, would it go under .trivial ?

**Comment by uranusjr** [comment]
I see. Does the `sync` command’s `--bare` option have the intended behaviour now? Since this PR does not change `sync`, it might be better to only mention adding `--bare` to `clean` in the commit message and news fragment.

**Comment by jcrotts** [comment]
One change was made to sync that removes one output line. I can change the commit message and news fragment if you think it would be clearer.

**Comment by uranusjr** [comment]
It would be best to either 1) remove mention of `sync` from fragment, or 2) use `sync`’s bare option to reduce output. I am fine with either, your call. (And if you opt for 1), another PR on `sync` would be nice as well!)

**Comment by uranusjr** [comment]
You don’t need to, I can squash on merge (but you can squash yourself as well, there’s no difference).

**Pull request closed without merging**
