### PR TITLE
Activate PIPENV_VENV_IN_PROJECT with --local

### LINKED ISSUE #2086: activate PIPENV_VENV_IN_PROJECT with --local

### PR DESCRIPTION
**Pull request by sivakar12**
Fixes #2086 
I think this works. How do I check? Given that the project is already in a virtualenv, can it create a virtualenv inside it?

### CODE REVIEW

**Comment by techalchemy** [comment]
Set PIPENV_IGNORE_VIRTUALENVS=1

Thanks for the contribution! If you get a chance, tests would also be helpful (in tests/integration/test_cli.py) — could be as simple as installing a package and making sure pipenv —venv outputs the right path

**Comment by sivakar12** [comment]
Thanks! I'll check. I'll write the tests too

**Comment by kennethreitz** [comment]
:-1:

**Comment by kennethreitz** [comment]
thanks for the suggestion, we need to be very careful about adding new flags, though. This feature is automatic if you just 'mkdir .venv'.

**Pull request closed without merging**
