### PR TITLE
Update manual

### PR DESCRIPTION
**Pull request by frostming**
### The fix

- Route the `pipenv --man` to the correct file.
- Add invoke task to generate manual.
- Update manual to the latest

### The checklist

* [ ] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by xilopaint** [comment]
When will this get merged?

**Comment by techalchemy** [comment]
Given the merge conflicts, probably when they get resolved...

**Comment by xilopaint** [comment]
> Given the merge conflicts, probably when they get resolved...

Ok, so let's wait for @frostming's action.

**Comment by techalchemy** [comment]
I think there is some preference to keep contributing docs in the repository root, can you use an include to pick it up if you convert it to rst?

**Comment by techalchemy** [comment]
Or else we can add some automation to generate the markdown version

**Comment by frostming** [comment]
@techalchemy Sure, I changed to use an autogenerated version.

**Comment by xilopaint** [comment]
Thank you for your work in this PR, guys. I'm new at pipenv and the manual will be very helpful. I'm looking forward the next release.

**Pull request merged**
