### PR TITLE
Update 2.7 default to 2.7.15

### PR DESCRIPTION
**Pull request by joshfriend**
https://mail.python.org/pipermail/python-list/2018-May/732755.html

### CODE REVIEW

**Comment by uranusjr** [comment]
Will need to wait until Pyenv makes a release (>1.2.3) https://github.com/pyenv/pyenv/releases

And Homebrew updates to match it https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyenv.rb

**Comment by joshfriend** [comment]
Thanks for the reminder, I'll get that done shortly...

**Comment by joshfriend** [comment]
https://github.com/Homebrew/homebrew-core/pull/27338

**Comment by uranusjr** [comment]
Excellent.

**Comment by techalchemy** [comment]
Thanks for being on top of this Josh!

**Pull request merged**
