### PR TITLE
Automate release workflow

### PR DESCRIPTION
**Pull request by techalchemy**
- Automatically release when tags are pushed to master
- Release automation will build wheel and sdist + upload to pypi
- Added test pypi as initial target
- Updated version update scripts to help with automatic version
  management

### CODE REVIEW

**Comment by techalchemy** [comment]
tagged reviewers for awareness -- will be adding release documentation

**Comment by techalchemy** [comment]
> I see it is uploading to test-pypi, is it a temporary solution or a standard workflow?

the `test.pypi.org` part will be a test to make sure the action works properly, my intention is to switch over to do real releases this way if everyone thinks it makes sense

**Comment by frostming** [comment]
It makes sense to me. I also tried the release workflow of `pythonfinder`, it works like a charm.

**Comment by techalchemy** [comment]
> It makes sense to me. I also tried the release workflow of `pythonfinder`, it works like a charm.

I didn't even realize you made a new release, that's awesome

**Pull request merged**
