### PR TITLE
Add docstrings to show short_help when running --help

### PR DESCRIPTION
**Pull request by sup**
Description
------------
This addresses #2381 by adding docstrings to cli commands which allows Click to display some informative help text when running --help. This change simply maps the existing `short_help` field to a docstring.

Moreover, this doesn't cause the truncation issue mentioned in #2381 because`short_help` is already defined and overrides the 45 character truncation Click uses by default. Indeed, running `pipenv --help` locally results in status quo behavior:

```
Commands:
  check      Checks for security vulnerabilities and against PEP 508 markers
             provided in Pipfile.
  clean      Uninstalls all packages not specified in Pipfile.lock.
  graph      Displays currently-installed dependency graph information.
  install    Installs provided packages and adds them to Pipfile, or (if none
             is given), installs all packages.
  lock       Generates Pipfile.lock.
  open       View a given module in your editor.
  run        Spawns a command installed into the virtualenv.
  shell      Spawns a shell within the virtualenv.
  sync       Installs all packages specified in Pipfile.lock.
  uninstall  Un-installs a provided package and removes it from Pipfile.
  update     Runs lock, then sync.
```

Result
------
```
$ pipenv check --help
Usage: pipenv check [OPTIONS] [ARGS]...

  Checks for security vulnerabilities and against PEP 508 markers provided
  in Pipfile.

Options:
  --three / --two     Use Python 3/2 when creating virtualenv.
  --python TEXT       Specify which version of Python virtualenv should use.
  --system            Use system Python.
  --unused TEXT       Given a code path, show potentially unused dependencies.
  -i, --ignore TEXT   Ignore specified vulnerability during safety checks.
  --pypi-mirror TEXT  Specify a PyPI mirror.
  -h, --help          Show this message and exit.
```

### CODE REVIEW

**Comment by erinxocon** [comment]
Hi @sup!  Thanks for this, I am not against changing this however I’m going to need BDFL (@kennethreitz 🙂) approval since it’s an API change technically.

**Comment by sup** [comment]
Sure thing!

**Comment by erinxocon** [comment]
BDFL gave their ok, merging!

**Comment by erinxocon** [comment]
Hey @sup, I messed up and merged the PR and then reverted it to a bug I thought was in this PR, but was not.  Could you reopen a PR so I can merge it proper?

**Comment by sup** [comment]
@erinxocon oh yeah sure thing! Thanks for the info!

**Pull request merged**
