### PR TITLE
Documentation: pip specifiers with Pipenv

### PR DESCRIPTION
**Pull request by trallard**
This PR adds details on the pip specifiers and how to use them in conjunction with pipenv

This is related to #2816

### CODE REVIEW

**Comment by uranusjr** [comment]
Thanks for putting time into this, I love it! I do wonder however whether it is a little bit too long. Most people would only need `>=` and `<=` (plus their open-ended counterparts), and maybe `≠`. It might be better to just “give a taste” of what is possible, and encourage people to read PEP 440 if they want more.

Using `==` is strongly discouraged since it prevents you from getting any updates at all, so it might be a good idea to intentionally leave it out (again, people can read PEP 440 if they need it). I also feel `~=X.Y` should be preferred to `==X.*`.

Finally, some of the commands in the write up are not very compatible across various platforms. `pipenv install requests> 2.19`, for example, would result in `pipenv install requests` and outputting stdout to a file named `2.19`, since `>` is the special character for [output redirection](https://robots.thoughtbot.com/input-output-redirection-in-the-shell). It is best practice to always put quotes around the requirement, like this:

```
$ pipenv install "requests>=1.4"
$ pipenv install "requests!=2.*"  # Not strictly required, but best practice to ALWAYS quote.
```

It would be nice if there is a little text explaining why quotes are recommended (since PEP 440 does not cover it).

**Comment by trallard** [comment]
👌🏼 thanks for the feedback @uranusjr, based on this I will apply the following changes:
- Remove the use of '==' 
- Add " " around the specifiers (along with a note saying why this is advised)
- Reword the last text (ref to pep 440) so that people actually check this for more advanced/specific cases

**Comment by trallard** [comment]
I have made the changes now and this should be less verbose while still being able to provide a good idea of how this work, let me know what you think

**Comment by uranusjr** [comment]
Waiting for CI to pass before I hit merge…

**Pull request merged**
