### PR TITLE
WIP: Make install editable option an option

### PR DESCRIPTION
**Pull request by mlouielu**
let the -e option show in `pipenv install -h` and to be an option.

### CODE REVIEW

**Comment by uranusjr** [comment]
ref #2279

**Comment by uranusjr** [comment]
Something’s wrong :/

**Comment by techalchemy** [comment]
Thanks for the PR!

the `-e ` flag is handled in about 40 different places in the codebase, so simply adding it as a flag is not going to work out here

I wish it were this simple, but unfortunately its' not, if you want to iterate on this I'm happy to point you in the right direction

**Comment by mlouielu** [comment]
@techalchemy @uranusjr yep, I found that it is handled in multiple places in the code... I'll dig it out and iterate this PR.

**Comment by techalchemy** [comment]
No worries and no rush, this one is gonna be a pain :p

**Comment by techalchemy** [comment]
does this belong in a subcommand with the `multiple` flag from click? That way we can have unlimited `editable` things?

**Comment by uranusjr** [comment]
Yes, `multiple=True` should be added. We should probably add a test case for that usage as well.

http://click.pocoo.org/5/options/#multiple-options

**Comment by techalchemy** [comment]
(you shoudl probably link to version 6)

**Comment by mlouielu** [comment]
OK, I'll add the multiple and the test

**Comment by kennethreitz** [comment]
i don't think this is neccessary, but thank you.

**Comment by kennethreitz** [comment]
everything after 'install' is passed to pip. it's a pip feature, not a pipenv feature.

**Comment by mgeisler** [comment]
> everything after 'install' is passed to pip. it's a pip feature, not a pipenv feature.

Oh, that's interesting! I didn't know that `pipenv install` worked like that. Is it documented anywhere?

**Comment by mgeisler** [comment]
I don't think the logic that is supposed to pass command line options to Pip really works as intended. Here I tried to use `--no-index` with `pipenv install`, but it tries to install a package named `--no-index`:
```
[mg]% pipenv install --no-index --find-links . foobar==1.2.3
Installing --no-index...
⠋/nix/store/lw18hsacf1h82yvwg89nn5nsns9hcxij-pipenv-2018.7.1/lib/python3.6/site-packages/pipenv/vendor/requirements/parser.py:44: UserWarning: Private repos not supported. Skipping.
  warnings.warn('Private repos not supported. Skipping.')
Traceback (most recent call last):
  ...
AttributeError: 'NoneType' object has no attribute 'specifier'
```

**Comment by kennethreitz** [comment]
that's not exactly how it works

**Pull request closed without merging**
