### PR TITLE
Adds environment name to PROMPT on Cmd, Cmder,ConEmu

### PR DESCRIPTION
**Pull request by gtalarico**
This PR makes cmd.exe and cmder/conemu show the virtual environment's name 
in those shell's prompt.

This edit could also be in `fork_cmder()` , but that would not fix `cmd.exe`.
I understand the entire section might need some re-work and clean up but until then this should be an easy and contained fix that will make a lot of windows users happy.

image

PS: this is my first PR for a large project

### CODE REVIEW

**Comment by gtalarico** [comment]
PS: This fixes https://github.com/pypa/pipenv/issues/2116

**Comment by techalchemy** [comment]
Is this really all it takes...

**Comment by techalchemy** [comment]
BTW we should upstream these to pew as well

**Comment by techalchemy** [comment]
@uranusjr This change is pretty small, while the 11.11 changes are somewhat large in scope.  I really like the idea of getting these improvements and quality of life fixes done, if you think these are ok (and we get an upstream pr to pew opened) we can consider point releasing for these

**Comment by uranusjr** [comment]
In general it is (`%PROMPT%` is essentially PS1 for cmd), but I wonder what consequences would it have on custom init scripts (`clink.lua` for example). Will it result in duplicate venv names, or put it in the wrong place? We’ll need to put this in the wild and see what happens. Yeah I’d say let’s do this.

**Comment by techalchemy** [comment]
Seems like a good reason to get this out before a minor release, we can work through that stuff.

**Pull request merged**
