### PR TITLE
dummy - To fix #3343

### LINKED ISSUE #3343: Warn about invalid extras during locking
From #3026.

### PR DESCRIPTION
**Pull request by snow8gaia**
<details>

<summary> Thank you for contributing to Pipenv!</summary>

<p>

### The issue

What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.

Always consider opening an issue first to describe your problem, so we can discuss what is the best way to amend it.  Note that if you do not describe the goal of this change or link to a related issue, the maintainers may close the PR without further review.

If your pull request makes a non-insignificant change to Pipenv, such as the user interface or intended functionality, please file a PEEP. 

    https://github.com/pypa/pipenv/blob/master/peeps/PEEP-000.md

### The fix

How does this pull request fix your problem? Did you consider any alternatives? Why is this the *best* solution, in your opinion?

### The checklist

* [x] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

</p>
</details>

### CODE REVIEW

**Comment by snow8gaia** [comment]
#3343

**Comment by snow8gaia** [comment]
Should I ignore these tests? They should not be failing.

**Comment by snow8gaia** [comment]
These failed.
1. `def test_https_dependency_links_install(self, PipenvInstance, pypi):` in pipenv\tests\integration\test_install_twists.py
https://github.com/pypa/pipenv/blame/master/tests/integration/test_install_twists.py#



2. `def test_complex_deps_lock_and_install_properly(PipenvInstance, pip_src_dir, pypi):` in pipenv\tests\integration\test_lock.py
https://github.com/pypa/pipenv/blame/master/tests/integration/test_lock.py#

Windows CI-
https://dev.azure.com/pypa/pipenv/_build/results?buildId=4833&view=ms.vss-test-web.build-test-results-tab

Linux CI
https://dev.azure.com/pypa/pipenv/_build/results?buildId=4834&view=ms.vss-test-web.build-test-results-tab

----

Let me know what to do about this ASAP.

**Comment by snow8gaia** [comment]
I need to find a way to check if my dev setup is correct.

- [ ] Find how to check dev setup for pipenv.

**Comment by snow8gaia** [comment]
unhelpful

- [x] Nothing on this on StackOverflow. But for related issues that are not present here.

1. https://stackoverflow.com/questions/8329485/unable-to-find-remote-helper-for-https-during-git-clone
2.  https://stackoverflow.com/questions/47618534/fatal-unable-to-find-remote-helper-for-https

- [x] Unhelpful docs. https://git-scm.com/docs/git-remote-helpers

**Comment by snow8gaia** [comment]
possibly Helpful

- [x] https://github.com/atom/apm/issues/753 Unable to find remote helper for 'git+https'

1. https://github.com/atom/apm/issues/753#issuecomment-344394832



- [x] https://ionic.zendesk.com/hc/en-us/articles/360000343828-Package-build-fails-with-error-fatal-Unable-to-find-remote-helper-for-git-https-

- [x] https://code.i-harness.com/en/q/7f190d

**Comment by snow8gaia** [comment]
- [x] https://code.i-harness.com/en/q/7f190d has multiple methods:

1. In my case nothing was successful, after a while looking what was happening I found this on my config file.
```
% cat ~/.gitconfig 
[user]
    email = xxxxxxx@gmail.com
    name = xxxxxx
[alias]
    g = grep -n -i --heading --break
[url "git+https://github.com/"]
    insteadOf = git@github.com:
[url "git+https://"]
    insteadOf = git://
```
After removing the url properties everything was working fine again.

**Comment by snow8gaia** [comment]
I think these failing tests should be ignored.

**Comment by snow8gaia** [comment]
Getting issues with dev environ again. This is one reason its so annoying to do this. Thanks to a part in https://pipenv.readthedocs.io/en/latest/dev/contributing/#run-the-tests 

Fix this first?

**Comment by frostming** [comment]
@snow8gaia Thanks for your efforts, we are not going to look at PRs until the CI issue is fixed. You can wait for it and just ignore the failures before it's done. #3298

**Comment by snow8gaia** [comment]
frostming  Thanks for the update.

**Comment by snow8gaia** [comment]
#3298 is merged. Sync the fork ->still 2 failing.

https://dev.azure.com/pypa/pipenv/_build/results?buildId=5560  -> the commit https://github.com/pypa/pipenv/commit/0984bab787158d6bb174e54876ab45f084dee960 

the function `def test_install_does_not_extrapolate_environ(PipenvInstance, pypi)` in https://github.com/pypa/pipenv/blame/0984bab787158d6bb174e54876ab45f084dee960/tests/integration/test_install_basic.py#

**Comment by snow8gaia** [comment]
frostming Ignore the failing tests, got it.

**Comment by snow8gaia** [comment]
https://pipenv.readthedocs.io/en/latest/dev/contributing/#steps-for-submitting-code

Step2 
- [ ] Run the tests locally.
Tests fail-> Using the CI checking this PR to say- passed all tests. -> Ignore tests.

Step3
- [ ] Write tests that demonstrate your bug or feature.
- [ ] Ensure that they fail.

**Comment by snow8gaia** [comment]
All checks pass.

**Comment by techalchemy** [comment]
this PR doesn't appear to carry any changes with it.  You don't need to rely on tests that are not related to the changes you are attempting to make but please don't open dummy PRs as a personal workbench.  Do feel free to open a work in progress PR when you have some working code for review

Closing this for now as it currently contains no changes

**Comment by snow8gaia** [comment]
Seen.

**Comment by snow8gaia** [comment]
Sorry for noupdates, delay, etc. permanently set my GitHub status to Busy.

1. Is 'issue #3343' already fixed? 
Anyways, I wrote some code, I think it works. Its in pipenv\core.py in def do_lock() -
  ```python
    # warn about invalid extras in Pipfile
    from .environment import Environment
    for section in pipfile_section:
        for k,v in pipfile[section].copy().items():
            if hasattr(v, "extras"):
                if k =! package__name.valid and package__name.is_installed(k):# check if extra is valid
                    raise exceptions.PipenvFileError(message="Invalid extra in Pipfile in [{0}] section".format(
                                    pipfile_section.replace("_", "-")))
```
2. Can this same PR be re-opened? I can't push my fork since some time.
Thanks.
---
 will try to reply quickly.

**Comment by frostming** [comment]
@snow8gaia We don't keep PRs without any meaningful change and just for testing.

If you have some working code you can push it to your fork repo and open another PR. Closing a PR won't cause you unable to push.

**Comment by snow8gaia** [comment]
Got any ideas for personal testing?

while syncing the local copy of the fork, commits are generated. Can't push them since the PR got closed. I'll try pushing it again.

edit: 

```
git add pipenv/core.py
git push origin master
```
Thanks a lot frostming. It works now. Earlier I hadn't added any code to the repo. Whenever I would sync the fork and then try to update the fork by  'git push origin master'. It would give this error message-
'''
To https://github.com/snow8gaia/pipenv.git
 ! [rejected]          master -> master (fetch first)
error: failed to push some refs to 'https://github.com/snow8gaia/pipenv.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
'''

**Comment by snow8gaia** [comment]
1. In your previous comment did you mean that the code snippet does not work? Or something else?
2. I have not committed the above snippet to the fork yet.

**[editing]**

**Comment by frostming** [comment]
> I have not committed the above snippet to the fork yet.

yeah it only contains updates of this PR for now. In case the remote repo rejects your push you need to do `git pull origin master` first to merge the changes you don't have in your local copy, then push will be fine.

**Comment by snow8gaia** [comment]
1. Assuming squash means-> combine multiple commits that sync fork with pypa/pipenv. 
not what I wanted -> https://github.com/pypa/pipenv/compare/master...snow8gaia:master

2. `if getattr(v, "extra") is not in project.installed_package_names:` from 
https://github.com/pypa/pipenv/commit/2026085f9e2b820e67af1c62c59113908ae416ef

3. hope 1&2 are fun. smiley emoji. 

4. i'll make a 'Pull request' soon.

<details>

<summary>to be clear</summary>

<p>
1. is not a complain
2. was meant to work; but turned out to be a error. I'll fix it.
3. (is sarcasm) but this(1) needs to improve.
Duplicate of #
</p>
</details>


----

I'll try to reply till 9:05PM (`timezone: Asia/Kolkata` )

**Comment by snow8gaia** [comment]
As far as I know, #3343 is not complete. I quit, i.e. not working on it anymore.
from creation of issue #3343: About 159 days ( 5 months, 1 week, 1 day )
Feel free to ask anything. 

<details>

<summary>(tautological statement) </summary>

<p>It might take a long time to get a reply.</p>

</details>

**Pull request closed without merging**
