### PR TITLE
Propose the use of dotenv to manage Pipenv environments

### PR DESCRIPTION
**Pull request by frostming**
This PR includes a PEEP describing the feature requested.

### CODE REVIEW

**Comment by frostming** [comment]
Related/similar:
* #3080 
* #3271

**Comment by techalchemy** [comment]
interesting. I don’t use direnv and didn’t know it doesn’t work on windows. The main issue we have raised about this approach has been that pipenv needs to be running already in order to load the dotenv file, which means it already has not loaded that file before running. 

The proposal would require separately loading and parsing `env` files before running any commands and then again during execution, which crosses contexts (things used for the state of the app runtime vs the app runner runtime). Conflating those is both confusing and demands extra context management by pipenv, which we would need to flesh out here. Between myself, Kenneth and @uranusjr we have said no to this at least 8 times, mostly for these reasons

**Comment by frostming** [comment]
> I don’t use direnv and didn’t know it doesn’t work on windows
I didn't check it through, just derived from the fact `cmd` or `batch` is not listed on the official website. This may be not true.

> The proposal would require separately loading and parsing env files before running any commands and then again during execution
Yes, I also understand that.

> Between myself, Kenneth and @uranusjr we have said no to this at least 8 times, mostly for these reasons
I didn't know the histories, lol. This is just opened for discussion and any feedbacks are welcomed.

**Comment by uranusjr** [comment]
I am more -0, i.e. not strongly against it, but does not feel it is a good idea.[*] I do wonder whether it is better to extrapolate `.envrc` instead of `.env`, so there is a clean separation between project and app settings. This would considerably increase the complexity, however.

[*]:  I am more in favour of having a project-level configuration file, e.g. pyproject.toml, but IIRC Kenneth is also against that.

**Comment by frostming** [comment]
I think we can stop here, thanks for everyone. We will just keep on the existing features.

**Pull request closed without merging**
