### PR TITLE
Bugfix/virtualenv location empty

### LINKED ISSUE #1648: Unable to install package in container
I was troubleshooting an opened bug (https://github.com/pypa/pipenv/issues/1639) that I seem to have run into. In trying to reproduce it, it seems like i bumped into another issue.

This looks similar to the closed https://github.com/pypa/pipenv/issues/1441 issue, however, the command `virtualenv --python=python3 myenv` did not error out as anticipated in the comments.

##### Expected result

I expected to see a `Pipfile` and `Pipfile.lock` in the `/tmp/test1` directory.

##### Actual result

Saw the strack trace above.

##### Steps to replicate

```
 saviles  ~  1  docker run --rm -ti fedora:27 /bin/bash
[root@0958ee759ab3 /]# dnf install -qy which
install-info: No such file or directory for /usr/share/info/which.info.gz
[root@0958ee759ab3 /]# pip3 install --user pipenv
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Collecting pipenv
  Downloading pipenv-11.2.0.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 412kB/s 
Collecting setuptools>=36.2.1 (from pipenv)
  Downloading setuptools-38.5.2-py2.py3-none-any.whl (490kB)
    100% |████████████████████████████████| 491kB 2.3MB/s 
Collecting virtualenv (from pipenv)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
    100% |████████████████████████████████| 1.8MB 810kB/s 
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading virtualenv_clone-0.3.0-py2.py3-none-any.whl
Installing collected packages: setuptools, virtualenv, virtualenv-clone, pipenv
  Running setup.py install for pipenv ... done
Successfully installed pipenv-11.2.0 setuptools-38.5.2 virtualenv-15.1.0 virtualenv-clone-0.3.0
[root@0958ee759ab3 /]# mkdir /tmp/test1
[root@0958ee759ab3 /]# cd /tmp/test1
[root@0958ee759ab3 test1]# python3 -m pipenv install requests
Warning: the environment variable LANG is not set!
We recommend setting this in ~/.profile (or equivalent) for proper expected behavior.
Creating a virtualenv for this project…
⠋Using base prefix '/usr'
New python executable in /root/.local/share/virtualenvs/test1-MiVIN7Yf/bin/python3
Also creating executable in /root/.local/share/virtualenvs/test1-MiVIN7Yf/bin/python
Installing setuptools, pip, wheel...done.

Virtualenv location: 
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.6/site-packages/pipenv/__main__.py", line 4, in <module>
    cli()
  File "/root/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/root/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.local/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/root/.local/lib/python3.6/site-packages/pipenv/cli.py", line 197, in install
    selective_upgrade=selective_upgrade
  File "/root/.local/lib/python3.6/site-packages/pipenv/core.py", line 1767, in do_install
    ensure_project(three=three, python=python, system=system, warn=True, deploy=deploy, skip_requirements=skip_requirements)
  File "/root/.local/lib/python3.6/site-packages/pipenv/core.py", line 688, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/root/.local/lib/python3.6/site-packages/pipenv/core.py", line 341, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/root/.local/lib/python3.6/site-packages/pipenv/project.py", line 439, in create_pipfile
    data[u'requires'] = {'python_version': python_version(self.which('python'))[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
```

[root@0958ee759ab3 test1]# python3 -m pipenv.help            
Pipenv version: `'11.2.0'`

Pipenv location: `'/root/.local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/bin/python3'`

Other Python installations in `PATH`:

  - `3.6`: `/usr/bin/python3.6m`
  - `3.6`: `/usr/bin/python3.6`
  - `3.6`: `/bin/python3.6`

  - `3.6.2`: `/usr/bin/python3`
  - `3.6.2`: `/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.2',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.15.6-300.fc27.x86_64',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP Mon Feb 26 18:43:03 UTC 2018',
 'python_full_version': '3.6.2',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `LS_COLORS`
  - `HOSTNAME`
  - `PWD`
  - `HOME`
  - `FBR`
  - `DISTTAG`
  - `FGC`
  - `TERM`
  - `SHLVL`
  - `PATH`
  - `_`
  - `OLDPWD`
  - `LC_CTYPE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `PWD`: `/tmp/test1`

---------------------------

Contents of `Pipfile` ('/tmp/test1/Pipfile'):

```toml

```
```
[root@0958ee759ab3 test1]# envname
bash: envname: command not found
[root@0958ee759ab3 test1]# virtualenv --python=python3 myenv
bash: virtualenv: command not found
[root@0958ee759ab3 test1]# python3 -m virtualenv --python=python3 myenv
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /tmp/test1/myenv/bin/python3
Also creating executable in /tmp/test1/myenv/bin/python
Installing setuptools, pip, wheel...done.
[root@0958ee759ab3 test1]# ls
Pipfile  myenv
[root@0958ee759ab3 test1]# 
```
(Edit: Formatting)

### PR DESCRIPTION
**Pull request by techalchemy**
Always find a real python path for pipfiles

- Fixes #1648, #1610
- Usese new finders for python

### CODE REVIEW

**Comment by kennethreitz** [comment]
This doesn’t honor user configuration.

**Comment by kennethreitz** [comment]
I think.

**Comment by techalchemy** [comment]
I think the opinionated approach might warrant consideration but someone somewhere has to decide which python to use when the user doesn’t tell us - I _think_ this still respects `PIPENV_DEFAULT_PYTHON_VERSION`. It would likely be safer to just use `sys.executable` as the default here, and fall back to `system_which(‘python’)` just depending how much you want to push python 3

**Comment by kennethreitz** [comment]
falling back to sys.executable

**Comment by bbarker** [comment]
looking forward to a new release with this possible fix for issues I described in #1610; I believe this release might fix it. I thought my issues had gone away, but upon creating a new virtualenv, the following results:

```
$ pipenv --python 3.6
Creating a virtualenv for this project…
Using /usr/bin/python3.6m (3.6.4) to create virtualenv…
⠋/usr/bin/python3.6: No module named pipenv.pew

Virtualenv location:
Creating a Pipfile for this project…
Traceback (most recent call last):
  File "/usr/local/bin/pipenv", line 11, in <module>
    load_entry_point('pipenv==11.5.3', 'console_scripts', 'pipenv')()
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 1043, in invoke
    return Command.invoke(self, ctx)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/vendor/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/cli.py", line 152, in cli
    core.ensure_project(three=three, python=python, warn=True, site_packages=site_packages)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 672, in ensure_project
    ensure_pipfile(validate=validate, skip_requirements=skip_requirements)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/core.py", line 321, in ensure_pipfile
    project.create_pipfile(python=python)
  File "/usr/local/lib/python3.6/dist-packages/pipenv/project.py", line 446, in create_pipfile
    data[u'requires'] = {'python_version': python_version(required_python)[:len('2.7')]}
TypeError: 'NoneType' object is not subscriptable
brandon@beb82dell0-DevContainer:~/workspace/pipenvtest
$ pipenv --py
/bin/python
brandon@beb82dell0-DevContainer:~/workspace/pipenvtest
$ ls -last /bin/py*
ls: cannot access '/bin/py*': No such file or directory
brandon@beb82dell0-DevContainer:~/workspace/pipenvtest
```

I also tried making a symbolic link to the python i wanted in `$HOME/bin` and putting that in my `$PATH` but that din't improve the situation.

Is there a way to manually tell pipenv which python to use?

**Comment by kennethreitz** [comment]
--python /path/to/python

**Comment by kennethreitz** [comment]
@bbarker make sure you're using the latest version. 

Please run `$ python -m pipenv.help` and paste the results.

**Comment by bbarker** [comment]
/usr/bin/python3.6m: No module named pipenv.help

**Comment by kennethreitz** [comment]
well sounds like you don't have pipenv installed properly :)

**Comment by bbarker** [comment]
This is how I did it as user root: (while building a docker container image): 

```
RUN wget https://bootstrap.pypa.io/get-pip.py && python3.6 get-pip.py && \
  python3.6 -m pip install pipenv
```

**Comment by kennethreitz** [comment]
pip install pipenv --upgrade?

**Comment by bbarker** [comment]
Hmm, I tried that in the dockerfile by appending `--upgrade` to the last command, as well as adding it as a separate command entirely (after all the other commands mentioned above), and have the same result in the end: 

```
$ pipenv --python 3.6                                                                                                                                                                                                                                                                                                                                                        
Creating a virtualenv for this project…                                                                                                                                                                                                                                                                                                                                      
Using /usr/bin/python3.6m (3.6.4) to create virtualenv…                                                                                                                                                                                                                                                                                                                      
⠋/usr/bin/python3.6: No module named pipenv.pew      
```

My pipenv exe looks like:

```
$ less /usr/local/bin/pipenv                                                                                                                                                                                                                                                                                                                                                 
#!/usr/bin/python3.6                                                                                                                                                                                                                                                                                                                                                         
# EASY-INSTALL-ENTRY-SCRIPT: 'pipenv==11.5.3','console_scripts','pipenv'                                                                                                                                                                                                                                                                                                     
__requires__ = 'pipenv==11.5.3'                                                                                                                                                                                                                                                                                                                                              
import re                                                                                                                                                                                                                                                                                                                                                                    
import sys                                                                                                                                                                                                                                                                                                                                                                   
from pkg_resources import load_entry_point                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                             
if __name__ == '__main__':                                                                                                                                                                                                                                                                                                                                                   
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])                                                                                                                                                                                                                                                                                                        
    sys.exit(                                                                                                                                                                                                                                                                                                                                                                
        load_entry_point('pipenv==11.5.3', 'console_scripts', 'pipenv')()                                                                                                                                                                                                                                                                                                    
    )                       
```

**Comment by bbarker** [comment]
Here's the installation text:

```
Step 32/36 : RUN wget https://bootstrap.pypa.io/get-pip.py && python3.6 get-pip.py &&   python3.6 -m pip install pipenv --upgrade
 ---> Running in 0282122e9a2f
--2018-03-12 14:30:40--  https://bootstrap.pypa.io/get-pip.py
Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.0.175, 151.101.64.175, 151.101.128.175, ...
Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.0.175|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1595408 (1.5M) [text/x-python]
Saving to: ‘get-pip.py’

     0K .......... .......... .......... .......... ..........  3% 2.54M 1s
    50K .......... .......... .......... .......... ..........  6% 6.43M 0s
   100K .......... .......... .......... .......... ..........  9% 16.7M 0s
   150K .......... .......... .......... .......... .......... 12% 8.31M 0s
   200K .......... .......... .......... .......... .......... 16% 13.2M 0s
   250K .......... .......... .......... .......... .......... 19% 11.2M 0s
   300K .......... .......... .......... .......... .......... 22% 14.1M 0s
   350K .......... .......... .......... .......... .......... 25% 9.19M 0s
   400K .......... .......... .......... .......... .......... 28% 14.5M 0s
   450K .......... .......... .......... .......... .......... 32% 2.92M 0s
   500K .......... .......... .......... .......... .......... 35% 8.54M 0s
   550K .......... .......... .......... .......... .......... 38% 11.5M 0s
   600K .......... .......... .......... .......... .......... 41% 12.9M 0s
   650K .......... .......... .......... .......... .......... 44% 12.0M 0s
   700K .......... .......... .......... .......... .......... 48% 16.9M 0s
   750K .......... .......... .......... .......... .......... 51% 10.9M 0s
   800K .......... .......... .......... .......... .......... 54% 14.4M 0s
   850K .......... .......... .......... .......... .......... 57% 18.5M 0s
   900K .......... .......... .......... .......... .......... 60% 13.1M 0s
   950K .......... .......... .......... .......... .......... 64% 14.9M 0s
  1000K .......... .......... .......... .......... .......... 67% 24.9M 0s
  1050K .......... .......... .......... .......... .......... 70% 10.0M 0s
  1100K .......... .......... .......... .......... .......... 73% 24.5M 0s
  1150K .......... .......... .......... .......... .......... 77% 9.21M 0s
  1200K .......... .......... .......... .......... .......... 80% 25.1M 0s
  1250K .......... .......... .......... .......... .......... 83% 17.4M 0s
  1300K .......... .......... .......... .......... .......... 86% 15.4M 0s
  1350K .......... .......... .......... .......... .......... 89% 17.2M 0s
  1400K .......... .......... .......... .......... .......... 93% 23.7M 0s
  1450K .......... .......... .......... .......... .......... 96% 18.4M 0s
  1500K .......... .......... .......... .......... .......... 99% 13.3M 0s
  1550K ........                                              100%  109M=0.1s

2018-03-12 14:30:41 (10.6 MB/s) - ‘get-pip.py’ saved [1595408/1595408]

The directory '/home/brandon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/brandon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading pip-9.0.1-py2.py3-none-any.whl (1.3MB)
Collecting setuptools
  Downloading setuptools-38.5.2-py2.py3-none-any.whl (490kB)
Collecting wheel
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-9.0.1 setuptools-38.5.2 wheel-0.30.0
The directory '/home/brandon/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/brandon/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pipenv
  Downloading pipenv-11.5.3.tar.gz (3.9MB)
Requirement already up-to-date: pip>=9.0.1 in /usr/local/lib/python3.6/dist-packages (from pipenv)
Requirement already up-to-date: setuptools>=36.2.1 in /usr/local/lib/python3.6/dist-packages (from pipenv)
Collecting virtualenv (from pipenv)
  Downloading virtualenv-15.1.0-py2.py3-none-any.whl (1.8MB)
Collecting virtualenv-clone>=0.2.5 (from pipenv)
  Downloading virtualenv_clone-0.3.0-py2.py3-none-any.whl
Installing collected packages: virtualenv, virtualenv-clone, pipenv
  Running setup.py install for pipenv: started
    Running setup.py install for pipenv: finished with status 'done'
Successfully installed pipenv-11.5.3 virtualenv-15.1.0 virtualenv-clone-0.3.0

```

It looks like there is a permission issue with `/home/brandon/.cache/pip/`; I'm not sure why in the Dockerfile it is trying to use `/home/brandon`/ since I clearly have specified `USER root` just before running this command.

**Pull request merged**
