### PR TITLE
Used invoke to update notpip to 22.0.3 and this in fact fixed the ifn…

### PR DESCRIPTION
**Pull request by matteius**
Used invoke to update notpip to 22.0.3 and this in fact fixed the infinity resolution.

This kind of took me several attempts to figure out using the invoke tasks we have in `pipenv`.

### The issue

https://github.com/pypa/pipenv/issues/4926

### The fix

This upgrades our `pipenv` version of `pip==22.0.3` aka `notpip`.

The infinity lock is gone, locking is deterministic and has a useful message:
```
matteius@matteius-VirtualBox:~$ pipenv lock
/home/matteius/.local/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 0.1.39ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed! 

ERROR:pip.subprocessor:[present-diagnostic] pip subprocess to install build dependencies exited with 1
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/resolver.py", line 743, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/resolver.py", line 704, in resolve_packages
[ResolutionFailure]:       results, resolver = resolve(
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/resolver.py", line 685, in resolve
[ResolutionFailure]:       return resolve_deps(
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/utils.py", line 1376, in resolve_deps
[ResolutionFailure]:       results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/utils.py", line 1105, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/home/matteius/pipenv/pipenv/utils.py", line 883, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: pip subprocess to install build dependencies exited with 1
```

### The checklist

* [X] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### If this is a patch to the `vendor` directory...
This is using the tasks to update pip by 
1.) adding pip version to the vendor.txt such that
2.) the invoke task `invoke vendoring.update` pulled in just the code relevant tot his fix.

### CODE REVIEW

**Comment by matteius** [comment]
Clearly I don't know how to upgrade pip gracefully, even using invoke and spending many hours on it.  But that is the answer to a number of folks problems with the locking.   My current branch though has other issues with dependencies now, for example:

```
Traceback (most recent call last):
  File "/home/matteius/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 2826, in get_specifier
    return Specifier(self.specifiers)
  File "/home/matteius/pipenv/pipenv/vendor/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pipenv.vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=4.5,<5.0'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/matteius/pipenv/pipenv/resolver.py", line 766, in <module>
    main()
  File "/home/matteius/pipenv/pipenv/resolver.py", line 760, in main
    _main(parsed.pre, parsed.clear, parsed.verbose, parsed.system, parsed.write,
  File "/home/matteius/pipenv/pipenv/resolver.py", line 743, in _main
    resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
  File "/home/matteius/pipenv/pipenv/resolver.py", line 704, in resolve_packages
    results, resolver = resolve(
  File "/home/matteius/pipenv/pipenv/resolver.py", line 685, in resolve
    return resolve_deps(
  File "/home/matteius/pipenv/pipenv/utils.py", line 1376, in resolve_deps
    results, hashes, markers_lookup, resolver, skipped = actually_resolve_deps(
  File "/home/matteius/pipenv/pipenv/utils.py", line 1108, in actually_resolve_deps
    results = resolver.clean_results()
  File "/home/matteius/pipenv/pipenv/utils.py", line 1023, in clean_results
    name, entry = format_requirement_for_lockfile(
  File "/home/matteius/pipenv/pipenv/utils.py", line 1045, in format_requirement_for_lockfile
    version = str(req.get_version())
  File "/home/matteius/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 2831, in get_version
    return pip_shims.shims.parse_version(self.get_specifier().version)
  File "/home/matteius/pipenv/pipenv/vendor/requirementslib/models/requirements.py", line 2828, in get_specifier
    return LegacySpecifier(self.specifiers)
  File "/home/matteius/pipenv/pipenv/vendor/packaging/specifiers.py", line 253, in __init__
    super().__init__(spec, prereleases)
  File "/home/matteius/pipenv/pipenv/vendor/packaging/specifiers.py", line 98, in __init__
    raise InvalidSpecifier(f"Invalid specifier: '{spec}'")
pipenv.vendor.packaging.specifiers.InvalidSpecifier: Invalid specifier: '>=4.5,<5.0'
```

**Comment by oz123** [comment]
@matteius clearly, it's not well documented. So, don't feel bad about it. 
This task seems huge, the last person who did it was @frostming . If you can explain us how to do it, we'll be thankful.

Also, as a side, note. This project is missing an architecture document or some reasoning on some of the earlier technical choices. IMHO, vendoring all that stuff, is just a PITA. There should have be a good python script to install pipenv after installing pip, and what should have followed was installing all the dependencies.

In gentoo, there is already a version with some vendored libraries stripped away. My goal is to create a version without any vendored packages. It might take some time though...

**Comment by frostming** [comment]
> IMHO, vendoring all that stuff, is just a PITA

The heaviest dependency is `pip`, but the internal APIs(hidden under `pip._internal` namespace) keep changing. It is impossible for Pipenv to support a wide range of pip versions. So it **has** to be vendored. Other dependencies under `pipenv/vendors` are not so hard to maintain, we just vendor them for stability.

Following the spirit, we can't directly fix code inside `patches` or `vendors` directory. Because each vendor is composed of 1)a pip dependency defined in the `vendors.txt` and 2) git patch files in `tasks/vendoring/patches` folder and all this must be able to be made up with full automation, no human interference. In this way, they will be easy to be devendored because most of the distros tend to do that.

> If you can explain us how to do it, we'll be thankful

So this command is for updating the vendors:

```
inv vendoring.update [package_name]
```

There are some options that can control the effect of the above command, but I can't tell you much details due to limited time.
But in short words, it will run the following steps:

1. Clear up the package directory to update
2. Download the wheels from PyPI and install them in the desired location
3. Download license files
4. Apply git patches to change the code
5. Rewrite import statements to the `vendors` namespace

The most complicated part is when you update a package, the patch files may or may not be able to apply, this part needs careful investigating. For me, I typically do it in this way:

1. Update the package version in `vendors.txt` or `patches.txt` manually
2. Run `inv vendoring update $package_name`, and if it will fail to apply patches
3. Commit the changes temporarily
4. Look at the patch file, copy each change to the new source files and discard those unneeded
5. Run `git diff --patch ${source_file_path} > tasks/vendoring/patches/${patch_file_name}`
6. Add the new changes to the last commit by `git commit --amend`
7. Repeat step 2 until the updating process succeeds

[This doc](https://github.dev/pypa/pipenv/blob/b092dd6cf86688ef1d4317d64f7af96d43d08139/RELEASING.md#L43-L44) also mentions how to update vendors.

@oz123 Thanks for improving the docs, you have to try it yourself, and/or look into the `tasks` code to have an idea of how it works. 

@matteius Thanks for taking care of upgrading `pip`, you may encounter massic CI failures, which is quite normal. Cheer up!

**Comment by matteius** [comment]
Thanks for the info @frostming -- that is similar to the path I was going down but the extra details are good to have, including the bits about maintain the patches and why its important to keep them able to apply.  Here is another can of worms, it seems that `pip==22.x` series doesn't support python 3.6 which I guess EOL'd 1 month and 3 weeks ago (23 Dec 2021)

**Comment by matteius** [comment]
Made a new PR following @frostming steps and tips, just upgrading targeted pip:  https://github.com/pypa/pipenv/pull/4966
This branch had too many wrong changes in it.

**Pull request closed without merging**
