### PR TITLE
Fix "ImportError: No module named weakref" in Python 2.7

### LINKED ISSUE #2961: pipenv install/graph fail with 2018.10.9: ImportError: No module named weakref
### Issue description

With pipenv 2018.10.9, all the pipenv commands fail (including `pipenv --support`): 

```pytb
Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipenv.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pipenv\__init__.py", line 23, in <module>
    from .cli import cli
  File "c:\python27\lib\site-packages\pipenv\cli\__init__.py", line 3, in <module>
    from .command import cli
  File "c:\python27\lib\site-packages\pipenv\cli\command.py", line 18, in <module>
    from .. import environments
  File "c:\python27\lib\site-packages\pipenv\environments.py", line 4, in <module>
    from .vendor.vistir.misc import fs_str
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\__init__.py", line 4, in <module>
    from .compat import NamedTemporaryFile, TemporaryDirectory, partialmethod
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\compat.py", line 34, in <module>
    from .backports.tempfile import NamedTemporaryFile
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\backports\__init__.py", line 5, in <module>
    from .tempfile import NamedTemporaryFile
  File "c:\python27\lib\site-packages\pipenv\vendor\vistir\backports\tempfile.py", line 16, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref
```

### Enviroment

* pip version: 10.0.1 and 18.1
* Python version: 2.7
* OS: Windows

### PR DESCRIPTION
**Pull request by greyli**
close #2961

### CODE REVIEW

**Comment by Jamim** [comment]
I think it's reasonable to squash the commits.

**Comment by immerrr** [comment]
Could you please also add `backports.shutil_get_terminal_size` in the same manner to also fix #2950 ?

**Comment by greyli** [comment]
@Jamim Thanks for the notice, but I think I did something wrong with Git.

**Comment by greyli** [comment]
Close in favor of #2967.

**Comment by Jamim** [comment]
@greyli I believe this article might be helpful:
[Git Tools - Rewriting History](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)

**Comment by techalchemy** [comment]
Git captures all activity in the reflog by default so it should be recoverable just by the original hash. Ping me on slack if you have trouble

**Comment by greyli** [comment]
@Jamim @immerrr @techalchemy Thanks for the tips!

**Pull request closed without merging**
