### PR TITLE
Pipfile: Add build and twine

### PR DESCRIPTION
**Pull request by cclauss**
Landing these two Python dependencies should make pull request #5836 easier to complete.
* https://pypi.org/project/build
* https://pypi.org/project/twine

@kalebmckale Your review, please.

### CODE REVIEW

**Comment by cclauss** [comment]
Just some notes on how I did this on my M1 Mac with two terminal tabs open...

% ` brew install python@3.7`
```
Error: python@3.7 has been disabled because it is deprecated upstream!
```
---
% ` docker run --rm -it python:3.7 bash`
---> Inside the docker container...
```bash
apt-get -qq update && apt-get install -y vim  # Or your favorite editor
git clone https://github.com/pypa/pipenv
cd pipenv
python3 -m venv .venv
source .venv/bin/activate
pip install --upgrade pip
pip install pipenv
vi Pipfile  # Add build and twine
pipenv update --clear
pipenv shell
    # Inside shell...
    pipenv update --clear && exit
git diff  # Verify the changes
pwd
# Do not `exit` yet!!
```
In another terminal tab...
% `docker ps`
```
CONTAINER ID   IMAGE                                                  COMMAND ...
413378ea9275   python:3.7                                             "bash" ...
```
% `docker cp 413378ea9275:/pipenv/Pipfil* .`

**Comment by kalebmckale** [comment]
I mean on an actual computer, it’s not a problem. On iPad, it’s not so easy. I did end up getting Python 3.7 installed, but the file took hours to go through the locking process and still eventually failed for some undetermined reason. `iSH`, the app I use, still has quite a few limitations to it.

**Comment by cclauss** [comment]
On iOS, i have been involved with these two apps but they are sort of prepackaged vs. iSH.
* https://apps.apple.com/us/app/pythonista-3
* https://apps.apple.com/ch/app/pyto-python-3

**Comment by kalebmckale** [comment]
Again, it’s not an issue of development. I personally use Pyto and Carnets. But compiling new versions of Python or running applications like locking Pipfile, as far as I know, cannot be done inside these apps. They don’t provide much of an isolated testing environment. However, I do like the convenience of developing on my iPad. It just makes some things a bit more tedious, but I generally like helping and doing what I can.

**Pull request merged**
