### PR TITLE
revert setuptools required upgrade.

### PR DESCRIPTION
**Pull request by matteius**
Setuptools upgrade in setup.py causing issues for some users.

### The fix

Fixes: https://github.com/pypa/pipenv/issues/5075

### The checklist

* [X] Associated issue
* [X] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by matteius** [comment]
> Which version is actually required?
@nomis It is a good question but from my experience many parts of pip and requirementslib pull in the latest setuptools and use it isolation anyway, and there is nothing that can be done about _that_.

> If pipenv doesn't need a newer version (and can be tested with the older version) it shouldn't be specifying it as a dependency.

It always specified this version as a dependency so this is rolling back my prior change, I don't believe we can drop it altogether as it is required.

**Comment by oz123** [comment]
Won't this still pull setup tools >=60?
Can we Block larger than 60 versions?

**Comment by matteius** [comment]
> Won't this still pull setup tools >=60? Can we Block larger than 60 versions?

This is just reverting it to what it was before, and it seems to work for the folks having the issue, which might just be ubuntu 22.0.4 specific.  I am not convinced that restrict it to less than the latest isn't going to cause different issues for folks that already have a newer version installed at the system level.  Doesn't seem worth it, and internally pipenv is going to pull in the latest setuptools anyway for use in isolation in some spots of requirementslib and pip.

**Comment by oz123** [comment]
Ok. But pulling this requires a new release (which I'm fine with) but I'm still not sure it's necessary. The issue has a documented solution in the comments. Won't this still be an issue when we upgrade setup tools later?

**Comment by matteius** [comment]
@oz123 I think it is what @nomis pointed out in the issue comments:

> When the setuptools/virtualenv/distutils bug is resolved then pipenv can depend on the newer version of those.

I did take a gamble on updating setuptools in the setup.py when dropping 3.6 support because it seemed like that version is really old, but now it seems this causes issues with whatever the system packaged setuptools or currently installed version is supposed to be so I think we should not restrict it newer yet.  I picked the `60.0.0` version based on which one they dropped 3.6 support in, but alas.   

Since pip and requirementslib seem to pull in the latest for some tasks anyway I find it is a complex relationship with setuptools. 

Is there a specific issue report in one of those other project @nomis that we could track on if its safe to try forcing the setuptools upgrade at that time?

**Comment by oz123** [comment]
Ok. Then let's merge this. But we need to keep track of the upstream bug somehow.

**Review by oz123 — APPROVED** [review]

**Pull request merged**
