### PR TITLE
Make sure we are not in a virtualenv if aborting

### LINKED ISSUE #2078: v11.10.1: initial `pipenv install` in existing virtualenv fails
<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/usr/local/lib/python3.6/site-packages/pipenv'`

Python location: `'/usr/local/bin/python'`

Other Python installations in `PATH`:

  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '4.16.3-1-ARCH',
 'platform_system': 'Linux',
 'platform_version': '#1 SMP PREEMPT Thu Apr 19 09:17:56 UTC 2018',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'linux'}
```

System environment variables:

  - `HOSTNAME`
  - `GPG_KEY`
  - `TERM`
  - `PYTHON_VERSION`
  - `PATH`
  - `PWD`
  - `LANG`
  - `PYTHON_PIP_VERSION`
  - `SHLVL`
  - `HOME`
  - `_`
  - `OLDPWD`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
  - `LANG`: `C.UTF-8`
  - `PWD`: `/app`

---------------------------

</details>

------------

##### Expected result

    Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
    Creating a Pipfile for this project…
    Pipfile.lock not found, creating…
    Locking [dev-packages] dependencies…
    Using pip: -i https://pypi.python.org/simple

                              ROUND 1                           
    Current constraints:

    Finding the best candidates:

    Finding secondary dependencies:
    ------------------------------------------------------------
    Result of round 1: stable, done

    Locking [packages] dependencies…
    Using pip: -i https://pypi.python.org/simple

                              ROUND 1                           
    Current constraints:

    Finding the best candidates:

    Finding secondary dependencies:
    ------------------------------------------------------------
    Result of round 1: stable, done

    Updated Pipfile.lock (625834)!
    Installing dependencies from Pipfile.lock (625834)…

##### Actual result

    Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead.
    Creating a Pipfile for this project…
    Warning: --system is intended to be used for Pipfile installation, not installation of specific packages. Aborting.
    See also: --deploy flag.

##### Steps to replicate

Requires pipenv v11.10.1. Not reproducible in v11.10.0. In an empty directory, run:

    $ virtualenv env
    $ source env/bin/activate
    $ pipenv install

### PR DESCRIPTION
**Pull request by pegler**
Fixes #2078

### CODE REVIEW

**Comment by uranusjr** [comment]
Thanks for the fix! The logic looks correct to me, but we probably want to add a comment there so make sure people reading the code in the future know exactly when (and why) we should abort. Would you be able to add this?

**Comment by pegler** [comment]
Done!

**Comment by techalchemy** [comment]
Thanks for the PR! Will merge after CI

**Comment by pegler** [comment]
hey @techalchemy, is there a release planned for sometime soon that will get this live?

**Comment by techalchemy** [comment]
@pegler in the next couple of days, we have some performance enhancements in the pipeline that I really want to get into the release if possible

**Comment by techalchemy** [comment]
If i have the time I will release sooner, depends how smoothly these all go

**Comment by pegler** [comment]
sounds good. thanks!!

**Pull request merged**
