### PR TITLE
Avoid ValueError on pyenv

### PR DESCRIPTION
**Pull request by EbiEbiEvidence**
### The issue

First, when I used it with pyenv, i got the below error.
```
  File "/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3/lib/python3.7/site-packages/pipenv/vendor/pythonfinder/models/python.py", line 117, in get_version_order
    version_paths.remove(version)
ValueError: list.remove(x): x not in list
```

Second, I checked variables around lines the error occurred.

https://github.com/pypa/pipenv/blob/cae8d76c210b9777e90aab76e9c4b0e53bb19cde/pipenv/vendor/pythonfinder/models/python.py#L99-L117

Finally, I found that `version_order` has duplicate versions.
`version_order`: 
[PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3'), PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/2.7.16'), PosixPath('/Users/EbiEbiEvidence/.anyenv/envs/pyenv/versions/3.7.3')]

This is caused by [common pyenv configuration](https://github.com/pyenv/pyenv#choosing-the-python-version) such as the below
```
$ pyenv global 3.7.3 2.7.16 3.7.3
```

# The fix
Remove the version only if it is contained in `version_paths`
https://github.com/pypa/pipenv/blob/cf087d98cb958aac3b81c523a8eba793baa52ac3/pipenv/vendor/pythonfinder/models/python.py#L116-L118

### CODE REVIEW

**Comment by techalchemy** [comment]
As a practice we don't make changes to vendored packages directly. Please open an issue and submit a PR to https://github.com/sarugaku/pythonfinder and we will consume the fix when we update our vendored dependencies.

Making these types of changes to vendored libraries is impossible to maintain over the long term. I will close this PR for now, but please carry the change over there (where I will merge it)

**Comment by EbiEbiEvidence** [comment]
Okay

**Comment by sid-kap** [comment]
@UniUniUnicode do you know what caused this error/when this error happens? Unfortunately I am running into it as well but I can't work around it because there hasn't been a pipenv release in almost a year

**Comment by uniuniunicode** [comment]
@sid-kap you should read this
https://github.com/sarugaku/pythonfinder/issues/70

when you type `$ pyenv global 3.xx 2.xx 3.xx`, the error occurs.

**Pull request closed without merging**
