### PR TITLE
Add section about PIPENV_CACHE_DIR in documentation

### PR DESCRIPTION
**Pull request by Purring**
Came across issue #1528 and realized no one added anything to the docs about it.

### CODE REVIEW

**Comment by uranusjr** [comment]
There really should be a whole page dedicated to environment variable usages. Care to split this to its own page? (And maybe add a line to indicate it is incomplete and ask for contributions.)

**Comment by Purring** [comment]
Sure, I'll split it up. I'll poke around the code for any envars and try to add them, too.

**Comment by uranusjr** [comment]
Thanks for the effort! There is also an section in the docs listing some environs (in the advanced page). You can use `pipenv --envs` to list some of them as well.

**Comment by Purring** [comment]
You said the advanced page in the docs already has sections related to environment variable usage, What's the use of putting them into their own page? Quite a few of the envars in

**Comment by uranusjr** [comment]
So they can be explained more detailed, like what you did with `PIPENV_CACHE_DIR`. I was thinking either pull the list to a seperate page (and turned into sections like your `PIPENV_CACHE_DIR` one), or add hyperlinks to the list items pointing to more detailed descriptions.

**Comment by techalchemy** [comment]
Can you just WIP tag this until you're done (unless you are dnoe now?)

**Comment by Purring** [comment]
I added a WIP to the issue title, sorry about that. I'll let you guys know when I'm finished, I think there are still a couple envars that need a section, and that should be done later tonight.

**Comment by Purring** [comment]
Alright, I'm finished. I only added envars that I understood, there are a couple like `PIPENV_SHELL` that seem like they should change the shell that runs when you do  `pipenv shell` but it doesn't do that. I'm not sure if those are bugs or if i'm just using them improperly, so i just left them out.

You can merge now, if you want to.

**Comment by uranusjr** [comment]
@Purring `PIPENV_SHELL` should do what you expected… but if it doesn’t it’s better to leave it out to prevent confusion.

**Pull request merged**
