### PR TITLE
Do not use red if it's no an error

### PR DESCRIPTION
**Pull request by yohanboniface**
screenshot-20180908121953-1086x144

Thanks :)

### CODE REVIEW

**Comment by techalchemy** [comment]
Hi there, thanks for the PR :) Any UI changes (and any changes at all) are going to require you to start with an Issue and in this case you will need to propose an enhancement by first creating a **PEEP** -- please see https://github.com/pypa/pipenv/blob/master/peeps/PEEP-001.md for more information on how to go about this

I appreciate that red is generally accepted as an error color, but Kenneth does make the call on UI decisions so this one will have to follow the process. Thanks again for your time, looking forward to the follow up proposal

**Comment by yohanboniface** [comment]
Sounds like "process over effectiveness". :(

And, did I just read this [there](https://github.com/pypa/pipenv/blob/master/peeps/PEEP-001.md)? ;)

> Avoid writing PEEPs, unless it seems absolutely neccessary, and in the best interest of the entire Python community.

Honnestly, I'm not going to write any PEEP to explain a BDFL that *red does mean error*. :)

**Comment by uranusjr** [comment]
Unfortunately, you do need to. The mapping of colour code to contextual meaning is highly cultural dependant, and is not as obvious as you would think. It makes sense for you, and likely people around you, but please do remember the world is a lot larger than that, and we need to assume less than we incline to. “Red = error” is not universal.

**Comment by yohanboniface** [comment]
Ah. Can you point me to the *PEEP* defining the colour scheme so I can suggest a modification of it? :)

**Comment by techalchemy** [comment]
No. We didn’t retroactivelt create enhancement proposals for things that already existed, the process is not meant to be complicated. It is meant to be explicit and straightforward and to separate technical decisions from interface design. If you want to introduce changes to the interface it should start as a proposal that can standardize, say, different types of information and what colors they should be. 

At that point we can probably find some accessibility guideline on the topic and take that info into account so that Kenneth can make centralized and informed design decisions without having to get bogged down in issues and PRs. We will have to run changes like this by him anyway, this process just makes it both easier and more uniform, it’s really not just me being a jerk :)

**Pull request closed without merging**
