### PR TITLE
remove cacert.pem bundle

### PR DESCRIPTION
**Pull request by nateprewitt**
Now that we've vendored in a modern version of Requests, we don't want this anymore.

### CODE REVIEW

**Comment by techalchemy** [comment]
Thanks Nate!

**Comment by danieldaeschle** [comment]
I am waiting for release to fix this. When will it be released?

**Comment by mystic-cg** [comment]
This problem still appeared.(Env: pip18.0, pipenv2018.7.1, win10, python3.6.4)

**Comment by uranusjr** [comment]
@mystic-cg Uninstall and install Pipenv again. pip sometimes has problems removing existing files from the system when you upgrade a package. Nothing we can do here.

**Pull request merged**
