### PR TITLE
Fixed UnicodeDecodeError happens on mbcs windows environment when package is installed from git+https source

### PR DESCRIPTION
**Pull request by TeeNak**
### The issue

https://github.com/pypa/pipenv/issues/3923

### The fix

There are two process in pipenv. one is pipenv itself and the other is resolver.py. while resolver.py emits output in utf-8, pipenv receives it as multibyte character set such as cp932.
I changed code so that the process watcher in delegator properly decode the text as utf-8.

### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by frostming** [comment]
Would be great if you can add a test case to verify the fix.

**Comment by TeeNak** [comment]
Hello @frostming 
Sorry for late reply. I needed to know more about this project.

As far as I understand, this fix was already covered by existing test. so adding new test doesn't improve the current situation.
The existing test which cover this fix is `tests/integration/test_install_uri.py:148 test_install_editable_git_tag`

When I run this test under the cp932 environment before my fix, this test gets following error.

```
> pipenv run pytest tests -k test_install_editable_git_tag
Loading .env environment variables…
================================================= test session starts ================================================= platform win32 -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: D:\src\python\pipenv, inifile: pytest.ini, testpaths: tests
plugins: flaky-3.5.3, forked-1.0.2, tap-2.3, xdist-1.29.0, pypi-0.1.1
gw0 [1] / gw1 [1] / gw2 [1] / gw3 [1] / gw4 [1] / gw5 [1] / gw6 [1] / gw7 [1]
F                                                                                                                [100%] ====================================================== FAILURES ======================================================= ____________________________________________ test_install_editable_git_tag ____________________________________________ [gw0] win32 -- Python 3.7.3 c:\users\user1\.virtualenvs\pipenv-vs77d6yl\scripts\python.exe

PipenvInstance_NoPyPI = <class 'tests.integration.conftest._PipenvInstance'>

    @pytest.mark.vcs
    @pytest.mark.tablib
    @pytest.mark.install
    @pytest.mark.needs_internet
    def test_install_editable_git_tag(PipenvInstance_NoPyPI):
        # This uses the real PyPI since we need Internet to access the Git
        # dependency anyway.
        with PipenvInstance_NoPyPI(chdir=True) as p:
            c = p.pipenv(
                "install -e git+https://github.com/benjaminp/six.git@1.11.0#egg=six"
            )
>           assert c.return_code == 0
E           AssertionError: assert 1 == 0
E            +  where 1 = <Command 'pipenv install -e git+https://github.com/benjaminp/six.git@1.11.0#egg=six'>.return_code

tests\integration\test_install_uri.py:155: AssertionError
------------------------------------------------ Captured stdout call ------------------------------------------------- $ pipenv install -e git+https://github.com/benjaminp/six.git@1.11.0#egg=six
Installing -e git+https://github.com/benjaminp/six.git@1.11.0#egg=six

Command failed...
------------------------------------------------ Captured stderr call ------------------------------------------------- 127.0.0.1 - - [15/Sep/2019 16:28:02] "GET /simple/six/ HTTP/1.1" 200 404
Creating a virtualenv for this project
Pipfile: C:\Users\user1\AppData\Local\Temp\pipenv-fmp78cmo-project\Pipfile
Using C:/Python37/python.exe (3.7.3) to create virtualenv
Already using interpreter C:\Python37\python.exe
Using base prefix 'C:\\Python37'
New python executable in C:\Users\user1\AppData\Local\Temp\pipenv-fmp78cmo-project\.venv\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Python37/python.exe


Successfully created virtual environment!
Virtualenv location: C:\Users\user1\AppData\Local\Temp\pipenv-fmp78cmo-project\.venv
Creating a Pipfile for this project

Adding six to Pipfile's [packages]

Installation Succeeded
Pipfile.lock not found, creating
Locking [dev-packages] dependencies
Locking [packages] dependencies

Building requirements...

Resolving dependencies...

Traceback (most recent call last):
  File "d:\src\python\pipenv\pipenv\utils.py", line 1105, in create_spinner
    yield sp
  File "d:\src\python\pipenv\pipenv\utils.py", line 1309, in venv_resolve_deps
    results = c.out.strip()
  File "d:\src\python\pipenv\pipenv\vendor\delegator.py", line 133, in out
    self.__out = self._pexpect_out
  File "d:\src\python\pipenv\pipenv\vendor\delegator.py", line 121, in _pexpect_out
    result += self.subprocess.read()
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 441, in read
    self.expect(self.delimiter)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\popen_spawn.py", line 93, in read_nonblocking
    buf += self._decoder.decode(incoming, final=False)
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 51: illegal multibyte sequence

Traceback (most recent call last):
  File "C:\Users\user1\.virtualenvs\pipenv-VS77d6Yl\Scripts\pipenv-script.py", line 11, in <module>
    load_entry_point('pipenv', 'console_scripts', 'pipenv')()
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\src\python\pipenv\pipenv\vendor\click\decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "d:\src\python\pipenv\pipenv\vendor\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "d:\src\python\pipenv\pipenv\vendor\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "d:\src\python\pipenv\pipenv\cli\command.py", line 253, in install
    site_packages=state.site_packages
  File "d:\src\python\pipenv\pipenv\core.py", line 2164, in do_install
    skip_lock=skip_lock,
  File "d:\src\python\pipenv\pipenv\core.py", line 1274, in do_init
    pypi_mirror=pypi_mirror,
  File "d:\src\python\pipenv\pipenv\core.py", line 1085, in do_lock
    keep_outdated=keep_outdated
  File "d:\src\python\pipenv\pipenv\utils.py", line 1309, in venv_resolve_deps
    results = c.out.strip()
  File "d:\src\python\pipenv\pipenv\vendor\delegator.py", line 133, in out
    self.__out = self._pexpect_out
  File "d:\src\python\pipenv\pipenv\vendor\delegator.py", line 121, in _pexpect_out
    result += self.subprocess.read()
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 441, in read
    self.expect(self.delimiter)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "d:\src\python\pipenv\pipenv\vendor\pexpect\popen_spawn.py", line 93, in read_nonblocking
    buf += self._decoder.decode(incoming, final=False)
UnicodeDecodeError: 'cp932' codec can't decode byte 0x82 in position 51: illegal multibyte sequence

================================================== warnings summary =================================================== tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
  D:\src\python\pipenv\tests\integration\conftest.py:79: RuntimeWarning: Cannot connect to GitHub via SSH
    'Cannot connect to GitHub via SSH', RuntimeWarning

tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
  D:\src\python\pipenv\tests\integration\conftest.py:82: RuntimeWarning: Will skip tests requiring SSH access to GitHub
    'Will skip tests requiring SSH access to GitHub', RuntimeWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===


===End Flaky Test Report===
=============================================== short test summary info =============================================== FAILED tests/integration/test_install_uri.py::test_install_editable_git_tag - AssertionError: assert 1 == 0
======================================= 1 failed, 16 warnings in 45.19 seconds ========================================
```


But after applying my fix, it gets following result without error.
```
> pipenv run pytest tests -k test_install_editable_git_tag
Loading .env environment variables…
================================================= test session starts ================================================= platform win32 -- Python 3.7.3, pytest-4.6.3, py-1.8.0, pluggy-0.12.0
rootdir: D:\src\python\pipenv, inifile: pytest.ini, testpaths: tests
plugins: flaky-3.5.3, forked-1.0.2, tap-2.3, xdist-1.29.0, pypi-0.1.1
gw0 [1] / gw1 [1] / gw2 [1] / gw3 [1] / gw4 [1] / gw5 [1] / gw6 [1] / gw7 [1]
.                                                                                                                [100%] ================================================== warnings summary =================================================== tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
tests\integration\conftest.py:79
  D:\src\python\pipenv\tests\integration\conftest.py:79: RuntimeWarning: Cannot connect to GitHub via SSH
    'Cannot connect to GitHub via SSH', RuntimeWarning

tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
tests\integration\conftest.py:82
  D:\src\python\pipenv\tests\integration\conftest.py:82: RuntimeWarning: Will skip tests requiring SSH access to GitHub
    'Will skip tests requiring SSH access to GitHub', RuntimeWarning

-- Docs: https://docs.pytest.org/en/latest/warnings.html
===Flaky Test Report===


===End Flaky Test Report===
======================================= 1 passed, 16 warnings in 51.67 seconds ========================================
```

**Comment by TeeNak** [comment]
Maybe it will be better if we had a mbcs windows test environment in Azure DevOps.

**Comment by techalchemy** [comment]
I am wondering if this fix is still relevant since we no longer write the JSON to the output stream, but instead we write a file which is loaded by the calling process. Granted we should handle encodings properly here but I would like to find a way to reproduce this failure

**Comment by TeeNak** [comment]
The error was caused from decoding stderr stream not from stdout stream. sometimes os error can contains strings in local language like 'アクセスが拒否されました。'.

The easiest way to emulate the error is to modify pipenv/resolver.py to raise exception with some unicode text after the PYTHONIOENCODING was changed to utf-8. like this.

``` python
# pipenv/resolver.py:788
def main():
    parser = get_parser()
    parsed, remaining = parser.parse_known_args()
    _patch_path(pipenv_site=parsed.pipenv_site)
    import warnings
    from pipenv.vendor.vistir.compat import ResourceWarning
    from pipenv.vendor.vistir.misc import replace_with_text_stream
    warnings.simplefilter("ignore", category=ResourceWarning)
    replace_with_text_stream("stdout")
    replace_with_text_stream("stderr")
    os.environ["PIP_DISABLE_PIP_VERSION_CHECK"] = str("1")
    os.environ["PYTHONIOENCODING"] = str("utf-8")
    raise Exception("アクセスが拒否されました。")  # <---
    os.environ["PYTHONUNBUFFERED"] = str("1")
    parsed = handle_parsed_args(parsed)
```

**Comment by techalchemy** [comment]
Thanks for the detailed example! 

In order to understand how critical this issue is -- is this completely broken for you without a fix applied?

**Comment by TeeNak** [comment]
Not so serious. now things have changed as I described in the original issue.
https://github.com/pypa/pipenv/issues/3923#issuecomment-623771372

**Pull request closed without merging**
