### PR TITLE
Remove always-True if-statement, and make function docstring accurate

### PR DESCRIPTION
**Pull request by thundergolfer**
### The issue

Addresses #3682 directly.

### The checklist

* [x] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

☝️I really don't think a `news/` entry is warranted for this change, but let me know if you disagree and I'll stick it in.

### CODE REVIEW

**Comment by thundergolfer** [comment]
Build failure is on integration testing and looks unrelated to my change. Will try a rebase later.

**Comment by frostming** [comment]
@thundergolfer Thanks. We will merge after CI tests are fixed(traced in another PR)

**Comment by thundergolfer** [comment]
@frostming Update?

**Comment by frostming** [comment]
@thundergolfer Sorry for the delay but we are waiting for the CI fixing PR merged.

**Pull request merged**
