### PR TITLE
Require “--python” values to exist

### PR DESCRIPTION
**Pull request by acdha**
This makes it easier for someone to realize when they have provided an invalid Python path without missing that message due to the sizable virtualenv traceback which follows it. I first encountered this when someone copy-and-pasted the example from the Conda documentation which has `--python=/path/to/anaconda/python`.

See #1862

### CODE REVIEW

**Comment by uranusjr** [comment]
This is still WIP so I might be commenting too early, but aside from absolute path `--python` also accepts version-like names (e.g. `3.6`, `2.7.10`). They need to be taken into consideration when validating the argument.

**Comment by acdha** [comment]
@uranusjr Yes — I ended up with a more conservative approach of only validating things which appear to be absolute paths to avoid that. It's worked in limited local testing but I'm still waiting for the test suite to finish running.

**Comment by techalchemy** [comment]
hey @acdha when you get a second can you update w/ current master so we can get tests running against this?

**Comment by techalchemy** [comment]
p.s sorry for the delay, tests were very broken (also sorry for the enormous pull you are going to have to do)

**Comment by techalchemy** [comment]
If you could revisit this at some point it would certainly make a good addition!

**Comment by acdha** [comment]
Sorry about the delays — I'm on parental leave the moment and don't have too much brainpower left for open-source 😀 

I rebased it against master and the tests are passing now on Travis so I removed the WIP prefix

**Comment by techalchemy** [comment]
Congrats and thanks a bunch!

P.S. We actually met at a conference at the LoC a long time ago, Back then I was working as the 'Curator of Executable Content' on an archive project, small world!

**Comment by acdha** [comment]
Ah, small world indeed! If you're ever near LC, feel free to stop by for
coffee.

Chris

**Pull request merged**
