### PR TITLE
Fix nondeterminism with environment markers #5239

### PR DESCRIPTION
**Pull request by bakhtiary**
Thank you for contributing to Pipenv!
No problem

### The issue

What is the thing you want to fix? Is it associated with an issue on GitHub? Please mention it.
Fixing #2927 5239

### The fix

We were using set to keep track of constraints, this changed their order leading to nondeterministic behaviour.

### The checklist

* [X] Associated issue
* [X] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix.rst`, `.feature.rst`, `.behavior.rst`, `.doc.rst`. `.vendor.rst`. or `.trivial.rst` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Review by matteius — APPROVED** [review]
The change makes sense to me; let's see how the test runner does and give @oz123  a chance to review too.

**Comment by oz123** [comment]
I'm not able to say much about the change, because the tests break. Should the test also be modified?

**Comment by bakhtiary** [comment]
hmmm, let me check the tests. I thought they might flaky, but this seems more than flake.

**Review by matteius — CHANGES_REQUESTED** [review]
Looks like there are some other places in the code that are still calling `.add()` to add a constraint.   The test failures have more details.

**Comment by bakhtiary** [comment]
> I'm not able to say much about the change, because the tests break. Should the test also be modified?

@oz123 I think it is Fixed now. most of the tests are passing, but I am not sure if what I have done is in line with what the algorithm expects.

**Comment by bakhtiary** [comment]
> Looks like there are some other places in the code that are still calling `.add()` to add a constraint. The test failures have more details.

fixed :D. I did actually run the tests, but then pushed when they started taking too long to finish :D.

**Comment by oz123** [comment]
The changes proposed look alright for me. However, I am wondering if ordered-set is a more appropriate solution.
It keeps the set, but adds order like a list.
An ordered set recipe can be floating around, and we can simply add it to our utils.

**Comment by matteius** [comment]
What about a sorted set vs an ordered set so that we get a consistent ordering regardless of the order things are added in?

**Comment by bakhtiary** [comment]
> The changes proposed look alright for me. However, I am wondering if ordered-set is a more appropriate solution.
> It keeps the set, but adds order like a list.
> An ordered set recipe can be floating around, and we can simply add it to our utils.

It is a good idea, specially that then it would maintain the functionality of the code the same. The main draw back of the list is that it can have duplicates and I don't have a clue what that would entail.

The con is that we'd have to add an extra library for the ordered set.

@matteius I don't think sorted set would work.

**Comment by bakhtiary** [comment]
One more option is to use a set and a list together in these 2 places and just check the set before inserting in the list.

**Comment by matteius** [comment]
@bakhtiary Well technically there is a SortedSet implementation that would work, but it would probably be simpler to use "use [collections.OrderedDict](https://docs.python.org/3/library/collections.html) from the Python standard library with just keys (and values as None) for the same purpose."  https://stackoverflow.com/questions/1653970/does-python-have-an-ordered-set

**Comment by bakhtiary** [comment]
But as @oz123 said we can also make our own ordered-set. We can make it using a list and a set or using the dict which is ordered since python 3.6. 

Or we can vendor either the OrderedSet or the ordered-set package.

These are all easy, just tell me which one and I'll get it done in a second :smiley_cat: I personally like the orderedset based on the dict Idea.

**Comment by matteius** [comment]
@bakhtiary I was thinking we could use` collections.OrderedDict` and then just `sorted(d.keys())` without having to add any new code.

**Comment by bakhtiary** [comment]
> @bakhtiary I was thinking we could use` collections.OrderedDict` and then just `sorted(d.keys())` without having to add any new code.

Oh I see. you are right. I believe the orderedDict will give us the keys in the order they were inserted. 

I think it would work. should I do it?

**Comment by matteius** [comment]
@bakhtiary Yeah `OrderedDict` feels like the cleanest solution to me in terms of least amount of memory and least additional code added.   We can probably sort the keys to be safe before we pass them as constraints, seeing as how the ordering upstream might change and I would be surprised if the ordering mattered for the actual correct application of the constraints.  We can debate this point about the sorting -- but what I really don't understand and I think to be true, is if we add a new package the markers for an existing package could completely convert to a different type of marker because technically the set and ordering could and would change when adding new dependencies.  Determinism is good though; consistency will probably be the next thing we will want to figure out in a separate effort.

**Comment by oz123** [comment]
I'm glad I triggered such a good discussion.
The package ordered-set has very unpleasant code to read imo. Compared to the original recipe 
Therehttps://github.com/ActiveState/code/blob/3b27230f418b714bc9a0f897cb8ea189c3515e99/recipes/Python/576696_OrderedSet_with_Weakrefs/README.md.

However, the idea of using a dictionary with keys only as a set replacement is my favorite.
It might not be straight forward for people who read the code in the future so it's worth adding a comment.

Also, we don't need ordereddict. All dictionaries in python 3.6+ are ordered. 

@bakhtiary sorry for sending you for another round of work on this. Thank you for your patience and work on this issue. 🤗

**Comment by bakhtiary** [comment]
I somehow accidentally closed this. I have opened another PR here: https://github.com/pypa/pipenv/pull/5286. feel free to revive this PR and delete the other one if there is a way.

**Comment by bakhtiary** [comment]
@matteius This PR some how was accidentally closed. It was not merged. I opened a new one here: https://github.com/pypa/pipenv/pull/5286

**Pull request merged**
