### PR TITLE
[fix] Update cacert.pem

### PR DESCRIPTION
**Pull request by nagaripratap**
Removed vulnerable e-tugra certificates
[Related]
https://github.com/pypa/pipenv/issues/5888

### CODE REVIEW

**Comment by matteius** [comment]
This should be done upstream in pip and then pipenv should vendor in the new version of pip, ideally.

**Comment by nagaripratap** [comment]
Please refer advisory database [vulns/certifi/PYSEC-2023-135.yaml](https://github.com/pypa/advisory-database/blob/9ac27e2dc49151238099cf755f08e142375119c1/vulns/certifi/PYSEC-2023-135.yaml#L8)

Alternatively, guide me which the other repo you are reffering ?

**Comment by matteius** [comment]
@nagaripratap its just that your modifying the internal cert of pip which we vendor in, it looks like pip already merged this upstream but hasn't cut a new release yet:  https://github.com/pypa/pip/pull/12206

**Comment by nagaripratap** [comment]
Ok got it 👍.

**Pull request merged**
