### PR TITLE
Fixed editable package with markers can not be locked

### PR DESCRIPTION
**Pull request by jxltom**
##### The issue

Fixed https://github.com/pypa/pipenv/issues/2902 and also added tests. Without this patch, the new added test will fail.

##### The fix

Fixed in upstream https://github.com/sarugaku/requirementslib/pull/71. If it can be accepted in upstream, then it can be merged here.

##### The checklist

* [x] Associated issue
* [x] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by jxltom** [comment]
No problem.

But how about the added tests? It will be nice to have tests which can make sure that later development won't break current working cases

**Comment by uranusjr** [comment]
I’d be fine if there is a test to ensure `pipenv lock -r` works, so I’ll merge if you take out the requirementslib patch (and probably change the news fragment). We’ll need to do it later though, otherwise it’ll break all CI.

**Comment by jxltom** [comment]
Great.

I've udpated the PR which removed the requirementslib patch as well as the news (since the test is too trivial)

Currently the CI is broken but it should be fine after https://github.com/sarugaku/requirementslib/pull/71 is merged from upstream.

**Comment by techalchemy** [comment]
I’ll release requirementslib in the next few days when I am sure we captured everything

**Comment by jxltom** [comment]
Update: it's ready for merge since https://github.com/pypa/pipenv/pull/2935 has been merged

**Pull request merged**
