### PR TITLE
Check whether inline tables are pinned during pipenv lock --keep-outdated flow

### LINKED ISSUE #2097: pipenv lock --keep-outdated doesn't update dependencies with extra details
Running `pipenv lock --keep-outdated` when a dependency with extras has changed in the Pipfile doesn't update the Pipfile.lock.

**Steps to replicate:**

Use these initial files:
<details>
<summary>Pipfile</summary>

```
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "==1.0.*"
raven = {extras = ["flask"], version = "==5.27.1"}
```

</details>

<details>
<summary>Pipfile.lock</summary>

```
{
    "_meta": {
        "hash": {
            "sha256": "4366926dcf71ad4f0e877f5ad9bb7de1a02e1177d0c2d7d1c4ad699f5bf25bdb"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "blinker": {
            "hashes": [
                "sha256:471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6"
            ],
            "version": "==1.4"
        },
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "contextlib2": {
            "hashes": [
                "sha256:509f9419ee91cdd00ba34443217d5ca51f5a364a404e1dce9e8979cea969ca48",
                "sha256:f5260a6e679d2ff42ec91ec5252f4eeffdcf21053db9113bd0a8e4d953769c00"
            ],
            "version": "==0.5.5"
        },
        "flask": {
            "hashes": [
                "sha256:cfc15b45622f9cfee6b5803723070fd0f489b3bd662179195e702cb95fd924c8",
                "sha256:dbe2a9f539f4d0fe26fa44c08d6e556e2a4a4dd3a3fb0550f39954cf57571363"
            ],
            "index": "pypi",
            "version": "==1.0.1"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "raven": {
            "hashes": [
                "sha256:1a7b595391c4557d8a9d9245138158130e43dcad02757f18d0a458e55c1e7162",
                "sha256:6d98c03c789e2d15dc61992e5e2c1ef0018c467d3ce7b9aa5830e7940a77b69a"
            ],
            "index": "pypi",
            "version": "==5.27.1"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}
```

</details>

<br>

Edit the raven declaration in the Pipfile to read `raven = {extras = ["flask"], version = "==6.7.0"}` and run `pipenv lock --keep-outdated`. The version of raven in the Pipfile.lock will not have updated.

The behaviour works as expected for dependencies with a string version - editing the Pipfile to read `raven = "==6.7.0"` and running `pipenv lock --keep-outdated` updates the lockfile as expected.

<details><summary>$ python -m pipenv.help output</summary>

Pipenv version: `'11.10.1'`

Pipenv location: `'/Users/greysteil/code/pipenv/pipenv'`

Python location: `'/usr/local/opt/python/bin/python3.6'`

Other Python installations in `PATH`:

  - `2.6`: `/usr/bin/python2.6`
  - `2.6`: `/usr/bin/python2.6`
  - `2.7`: `/Users/greysteil/.pyenv/shims/python2.7`
  - `2.7`: `/Users/greysteil/.pyenv/shims/python2.7`
  - `2.7`: `/usr/bin/python2.7`
  - `3.5`: `/Users/greysteil/.pyenv/shims/python3.5`
  - `3.6`: `/usr/local/bin/python3.6m`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/Users/greysteil/.pyenv/shims/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`
  - `3.6`: `/usr/local/bin/python3.6`

  - `3.6.5`: `/usr/local/bin/python`
  - `2.7.14`: `/Users/greysteil/.pyenv/shims/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `3.6.5`: `/usr/local/bin/python`
  - `2.7.10`: `/usr/bin/python`
  - `2.7.14`: `/Users/greysteil/.pyenv/shims/python2`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/Users/greysteil/.pyenv/shims/python3`
  - `3.6.5`: `/usr/local/bin/python3`
  - `3.6.5`: `/usr/local/bin/python3`

PEP 508 Information:

```
{'implementation_name': 'cpython',
 'implementation_version': '3.6.5',
 'os_name': 'posix',
 'platform_machine': 'x86_64',
 'platform_python_implementation': 'CPython',
 'platform_release': '16.7.0',
 'platform_system': 'Darwin',
 'platform_version': 'Darwin Kernel Version 16.7.0: Wed Oct  4 00:17:00 PDT '
                     '2017; root:xnu-3789.71.6~1/RELEASE_X86_64',
 'python_full_version': '3.6.5',
 'python_version': '3.6',
 'sys_platform': 'darwin'}
```

System environment variables:

  - `TERM_PROGRAM`
  - `PYENV_ROOT`
  - `SHELL`
  - `TERM`
  - `CLICOLOR`
  - `TMPDIR`
  - `Apple_PubSub_Socket_Render`
  - `TERM_PROGRAM_VERSION`
  - `TERM_SESSION_ID`
  - `PYENV_VERSION`
  - `USER`
  - `SSH_AUTH_SOCK`
  - `PYENV_DIR`
  - `__CF_USER_TEXT_ENCODING`
  - `LSCOLORS`
  - `PATH`
  - `PWD`
  - `EDITOR`
  - `LANG`
  - `PYENV_HOOK_PATH`
  - `XPC_FLAGS`
  - `RBENV_SHELL`
  - `XPC_SERVICE_NAME`
  - `SHLVL`
  - `HOME`
  - `PYENV_SHELL`
  - `LOGNAME`
  - `SECURITYSESSIONID`
  - `PYTHONDONTWRITEBYTECODE`
  - `PIP_PYTHON_PATH`

Pipenv–specific environment variables:

Debug–specific environment variables:

  - `PATH`: `/usr/local/bin:/usr/local/Cellar/pyenv/1.2.3/libexec:/Users/greysteil/.pyenv/plugins/pyenv-virtualenv/bin:/Users/greysteil/.pyenv/plugins/pyenv-update/bin:/Users/greysteil/.pyenv/plugins/pyenv-installer/bin:/Users/greysteil/.pyenv/plugins/pyenv-doctor/bin:/Users/greysteil/.pyenv/shims:/Users/greysteil/.pyenv/bin:/Users/greysteil/.cargo/bin:/usr/local/heroku/bin:/Users/greysteil/.rbenv/shims:/usr/local/bin:./node_modules/.bin:.bundle/binstubs:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/Library/TeX/texbin:/usr/local/sbin`
  - `SHELL`: `/bin/bash`
  - `EDITOR`: `subl -w`
  - `LANG`: `en_GB.UTF-8`
  - `PWD`: `/Users/greysteil/code/python-test`

---------------------------

Contents of `Pipfile` ('/Users/greysteil/code/python-test/Pipfile'):

```toml
[[source]]
url = "https://pypi.python.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = "==1.0.*"
raven = {extras = ["flask"], version = "==5.27.1"}

```

Contents of `Pipfile.lock` ('/Users/greysteil/code/python-test/Pipfile.lock'):

```json
{
    "_meta": {
        "hash": {
            "sha256": "4366926dcf71ad4f0e877f5ad9bb7de1a02e1177d0c2d7d1c4ad699f5bf25bdb"
        },
        "pipfile-spec": 6,
        "requires": {},
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.python.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "blinker": {
            "hashes": [
                "sha256:471aee25f3992bd325afa3772f1063dbdbbca947a041b8b89466dc00d606f8b6"
            ],
            "version": "==1.4"
        },
        "click": {
            "hashes": [
                "sha256:29f99fc6125fbc931b758dc053b3114e55c77a6e4c6c3a2674a2dc986016381d",
                "sha256:f15516df478d5a56180fbf80e68f206010e6d160fc39fa508b65e035fd75130b"
            ],
            "version": "==6.7"
        },
        "contextlib2": {
            "hashes": [
                "sha256:509f9419ee91cdd00ba34443217d5ca51f5a364a404e1dce9e8979cea969ca48",
                "sha256:f5260a6e679d2ff42ec91ec5252f4eeffdcf21053db9113bd0a8e4d953769c00"
            ],
            "version": "==0.5.5"
        },
        "flask": {
            "hashes": [
                "sha256:cfc15b45622f9cfee6b5803723070fd0f489b3bd662179195e702cb95fd924c8",
                "sha256:dbe2a9f539f4d0fe26fa44c08d6e556e2a4a4dd3a3fb0550f39954cf57571363"
            ],
            "index": "pypi",
            "version": "==1.0.1"
        },
        "itsdangerous": {
            "hashes": [
                "sha256:cbb3fcf8d3e33df861709ecaf89d9e6629cff0a217bc2848f1b41cd30d360519"
            ],
            "version": "==0.24"
        },
        "jinja2": {
            "hashes": [
                "sha256:74c935a1b8bb9a3947c50a54766a969d4846290e1e788ea44c1392163723c3bd",
                "sha256:f84be1bb0040caca4cea721fcbbbbd61f9be9464ca236387158b0feea01914a4"
            ],
            "version": "==2.10"
        },
        "markupsafe": {
            "hashes": [
                "sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665"
            ],
            "version": "==1.0"
        },
        "raven": {
            "hashes": [
                "sha256:1a7b595391c4557d8a9d9245138158130e43dcad02757f18d0a458e55c1e7162",
                "sha256:6d98c03c789e2d15dc61992e5e2c1ef0018c467d3ce7b9aa5830e7940a77b69a"
            ],
            "index": "pypi",
            "version": "==5.27.1"
        },
        "werkzeug": {
            "hashes": [
                "sha256:c3fd7a7d41976d9f44db327260e263132466836cef6f91512889ed60ad26557c",
                "sha256:d5da73735293558eb1651ee2fddc4d0dedcfa06538b8813a2e20011583c9e49b"
            ],
            "version": "==0.14.1"
        }
    },
    "develop": {}
}

```
</details>

### PR DESCRIPTION
**Pull request by greysteil**
Fixes #2097.

Previously, we were passing an `InlineTableElement` to `is_pinned`, which always returns false for non-strings.

### CODE REVIEW

**Comment by uranusjr** [comment]
I feel this check should be done inside `is_pinned()` instead.

**Comment by greysteil** [comment]
@uranusjr - updated.

**Comment by uranusjr** [comment]
Not sure if checking for `get` is a good idea here 🤔 I’d probably do something like

```
if isinstance(val, dict):   # Maybe collections.abc.Mapping is better?
    val = val.get('version')
return isinstance(val, six.string_types) and '==' in val
```

**Comment by greysteil** [comment]
The object is a `InlineTableElement`, but checking for that felt a bit implementation specific. I can switch it over if you prefer, though?

**Comment by uranusjr** [comment]
Yeah `InlineTableElement` is too implementation specific; checking for `Mapping` is probably best. Something like

```
try:
    from collections.abc import Mapping
except ImportError:
    from collections import Mapping
```

and replace `dict` with `Mapping` in the above snippet. This makes sure we’re checking for a dict-like interface (but not necessarily `dict`), not just `get` (which is too generic).

**Comment by greysteil** [comment]
On closer inspection, InlineTableElement doesn't inherit from Mapping - it implements the API itself in `AbstractTable`. Could check for `Mapping` or that?

**Comment by uranusjr** [comment]
@greysteil `Mapping` is an [abstract base class](https://docs.python.org/3/library/abc.html), or ABC. It does not need to be inherited directly; Python does some metaclass magic so an `isinstance` check against them only checks for the *interface*, not the inheritance chain. By checking against `Mapping` we ensure `val` has a dict-like behaviour for reading, which prettytoml table classes have. It should cover the `AbstractTable` case (although there’s no harm checking for it).

**Comment by greysteil** [comment]
Interesting - I had no idea. That's pretty cool!

Tested locally and the `AbstractTable` check is necessary here - must be something missing from its implementation that is causing the ABC check to fail. With the extra check everything works, though.

**Comment by greysteil** [comment]
Realised this could be easily broken by a future refactor, so I've written a test for it. There were no other integration tests for `--keep-outdated`, so I've made sure it covers the other tricky case I've seen in the past (PEP 423 name normalisation).

Apologies if the Python is awful! 🐒

**Comment by techalchemy** [comment]
So is the issue here that pinned things become unpinned?

**Comment by greysteil** [comment]
> So is the issue here that pinned things become unpinned?

The issue is that complex requirements are treated as if they were unpinned, even if they're pinned.

The `--keep-outdated` logic loops through each dependency that isn't pinned and sets its value to whatever it was before. It doesn't change any values that are pinned because it knows that changing the value in the lockfile for a pinned version could only be a mistake.

Previously, that logic thought that a requirement like `{version = "==2.18.0"}` was unpinned, even though it is clearly pinned. As a result, if the user changed it to `{version = "==2.18.4"}` the resolution process would pick up the correct new version, but the `--keep-outdated` loop would set the lockfile version back to its old value of `2.18.0`.

FWIW, there is another bug lurking in the above, that this PR doesn't fix. If a user has `2.18.0` in their lockfile and changes a requirement from `>=2.18.0` to `>=2.18.4` then the `--keep-outdated` logic will preserve that `2.18.0` in their lockfile, even though it is now invalid. Fixing this would require adding a requirement checking step in the `--keep-outdated` section that checks whether then new requirement is met. I think that should be done in a separate PR, since it's a separate bug (and rarer, given how people write Pipfiles).

**Comment by greysteil** [comment]
I'm guessing the test here needs the same attention as #2111 to not hit the internet? I have absolutely no idea how to do that... 🐒

**Comment by uranusjr** [comment]
@greysteil I’ll handle this.

**Comment by uranusjr** [comment]
Oh wait nothing needs to change here. `PipenvInstance` does the right thing automatically if you leave out the `[[source]]` section. This one is good to go.

**Comment by techalchemy** [comment]
Thanks for the PR and the explanation that makes a ton of sense.

**Pull request merged**
