### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by uranusjr**
Removed ppa mentions from documentation, and re-organised the page a bit to make it structurally easier to upderstand.

Both the documentation's front page and README.rst now actively refer to the page so user can be directed to better installation methods.

Also fixed many Sphinx warnings during documentation builds.

### CODE REVIEW

**Comment by uranusjr** [comment]
Why Buildkite why

**Comment by mlouielu** [comment]
small typo: upderstand -> understand

**Comment by mlouielu** [comment]
README.rst -> .md

**Comment by techalchemy** [comment]
+1 thanks for the cleanup :D

**Pull request merged**
