### PR TITLE
Introduced --local option in pipenv install to create VENV within project

### PR DESCRIPTION
**Pull request by GitShaffi**
### The issue

Fixes issue activate PIPENV_VENV_IN_PROJECT with --local #2086
    https://github.com/pypa/pipenv/issues/2086

### The fix

Have introduced --local option to pipenv install which will create the .venv dir within the project

Let me know if there are any feedbacks.

### The checklist

* [x] Associated issue
* [ ] A news fragment in the `news/` directory to describe this fix with the extension `.bugfix`, `.feature`, `.behavior`, `.doc`. `.vendor`. or `.trivial` (this will appear in the release changelog). Use semantic line breaks and name the file after the issue number or the PR #.

### CODE REVIEW

**Comment by kennethreitz** [comment]
this requires a PEEP

**Comment by GitShaffi** [comment]
> this requires a PEEP

@kennethreitz This exists in the [11.11.0](https://github.com/pypa/pipenv/milestone/4). Should one of the maintainers create the PEEP or can I go ahead creating a new PEEP?

**Comment by techalchemy** [comment]
Yes the relevant milestone was created after Kenneth opened the issue (because what he says goes) but he has been kind of undecided on it since then. Just because we put something in a milestone doesn’t mean it’s happening or that it’s a good idea. The PEEP process is helpful for everyone for getting things formalized a bit

**Comment by pirate** [comment]
Apologies for hijacking this PR for a tangent, but it would also be great to be able to put a directive in the `Pipfile` that forces it to create the venv locally, e.g.:

```ini
[pipenv]
venv_in_project = true
ignore_virtualenvs = true
...
```

I've seen this requested elsewhere and I know it would save people a lot of trouble, `direnv` is not a solution that works for everyone and it would be great to be able to put all config in one place.

**Comment by techalchemy** [comment]
Please don't jump on pull requests to make a case for implementing a feature, if you would like to see a configuration file or config options in the pipfile please propose that via a `PEEP` -- not in someone else's unrelated pr.

**Comment by techalchemy** [comment]
@GitShaffi feel free to formalize a `PEEP` for this if Kenneth has requested it -- I believe he also requested the feature, so I see no problem with merging a PEEP on the topic

**Comment by techalchemy** [comment]
Also sorry this has taken so long, we had a _lot_ of issues to resolve before we could consider merging this

**Comment by matteius** [comment]
Just noting here that the current status of this seems to be the variable `PIPENV_VENV_IN_PROJECT` exists and is used to put the virtualenv within the project directory, but that there is no current `--local` option flag for these.  Seems like it could be useful for parity with the env variable, but that this PR is way out of date.

**Comment by matteius** [comment]
Closing this in favor of the current solution `PIPENV_VENV_IN_PROJECT` environment variable.

**Pull request closed without merging**
